apiVersion: v1
kind: Service
metadata:
  name: admin-core-service
  namespace: default
spec:
  selector:
    app: admin-core-service
  ports:
    - name: http
      port: 8072
      targetPort: 8072
  type: NodePort
