apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: default
spec:
  selector:
    app: assessment-service
  ports:
    - name: http
      port: 8074
      targetPort: 8074
  type: NodePort
