apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: default
spec:
  selector:
    app: media-service
  ports:
    - name: http
      port: 8075
      targetPort: 8075
  type: NodePort
