#!/usr/bin/env bash

set -euo pipefail

# setup-secrets.sh
# Interactive helper to create/update a .env file for first-time deployments.
# It prompts for key environment variables used by the app and writes them to .env.

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ENV_FILE="$ROOT_DIR/.env"

timestamp() { date +"%Y%m%d-%H%M%S"; }

backup_if_exists() {
  if [[ -f "$ENV_FILE" ]]; then
    local backup_file="$ENV_FILE.bak-$(timestamp)"
    cp "$ENV_FILE" "$backup_file"
    echo "Backed up existing .env to $backup_file"
  fi
}

prompt() {
  local var_name="$1"
  local prompt_text="$2"
  local default_val="${3:-}"

  local current_val="${!var_name:-}"
  local effective_default="$current_val"
  if [[ -z "$effective_default" ]]; then
    effective_default="$default_val"
  fi

  if [[ -n "$effective_default" ]]; then
    read -r -p "$prompt_text [$effective_default]: " input || true
    if [[ -z "${input:-}" ]]; then
      printf -v "$var_name" '%s' "$effective_default"
    else
      printf -v "$var_name" '%s' "$input"
    fi
  else
    read -r -p "$prompt_text: " input || true
    printf -v "$var_name" '%s' "${input:-}"
  fi
}

require_non_empty() {
  local name="$1"; local value="$2"; local pretty="$3"
  if [[ -z "$value" ]]; then
    echo "Error: $pretty ($name) cannot be empty." >&2
    exit 1
  fi
}

validate_url() {
  local url="$1"; local pretty="$2"
  if [[ -n "$url" && ! "$url" =~ ^https?://.+ ]]; then
    echo "Error: $pretty must start with http:// or https://" >&2
    exit 1
  fi
}

echo "\n=== Secrets/Env Setup ==="
echo "This will create or update .env at: $ENV_FILE"

# Core URLs
prompt VITE_BACKEND_URL "Backend Base URL (API)" "https://backend-stage.vacademy.io"
prompt VITE_API_BASE_URL "Legacy API Base URL (leave empty to mirror backend URL)" ""
prompt VITE_LEARNER_DASHBOARD_URL "Learner Dashboard URL" "https://learner.vacademy.io"
prompt VITE_TEACHER_DASHBOARD_URL "Teacher/Admin Dashboard URL" "https://dash.vacademy.io"

validate_url "$VITE_BACKEND_URL" "Backend Base URL"
[[ -n "${VITE_API_BASE_URL:-}" ]] && validate_url "$VITE_API_BASE_URL" "Legacy API Base URL"
validate_url "$VITE_LEARNER_DASHBOARD_URL" "Learner Dashboard URL"
validate_url "$VITE_TEACHER_DASHBOARD_URL" "Teacher/Admin Dashboard URL"

require_non_empty VITE_BACKEND_URL "$VITE_BACKEND_URL" "Backend Base URL"

if [[ -z "${VITE_API_BASE_URL:-}" ]]; then
  VITE_API_BASE_URL="$VITE_BACKEND_URL"
fi

# Institute IDs
prompt VITE_INSTITUTE_ID "Default Institute ID" "c70f40a5-e4d3-4b6c-a498-e612d0d4b133"
prompt VITE_CODE_CIRCLE_INSTITUTE_ID "Code Circle Institute ID (optional)" "dd9b9687-56ee-467a-9fc4-8c5835eae7f9"
prompt VITE_HOLISTIC_INSTITUTE_ID "Holistic Institute ID (optional)" "bd9f2362-84d1-4e01-9762-a5196f9bac80"

# Optional Firebase (press Enter to skip)
prompt VITE_FIREBASE_API_KEY "Firebase API Key" ""
prompt VITE_FIREBASE_AUTH_DOMAIN "Firebase Auth Domain" ""
prompt VITE_FIREBASE_PROJECT_ID "Firebase Project ID" ""
prompt VITE_FIREBASE_STORAGE_BUCKET "Firebase Storage Bucket" ""
prompt VITE_FIREBASE_MESSAGING_SENDER_ID "Firebase Messaging Sender ID" ""
prompt VITE_FIREBASE_APP_ID "Firebase App ID" ""
prompt VITE_FIREBASE_MEASUREMENT_ID "Firebase Measurement ID" ""

backup_if_exists

cat > "$ENV_FILE" <<EOF
# Generated by setup-secrets.sh on $(date -Iseconds)

# Core URLs
VITE_BACKEND_URL=$VITE_BACKEND_URL
VITE_API_BASE_URL=$VITE_API_BASE_URL
VITE_LEARNER_DASHBOARD_URL=$VITE_LEARNER_DASHBOARD_URL
VITE_TEACHER_DASHBOARD_URL=$VITE_TEACHER_DASHBOARD_URL

# Institutes
VITE_INSTITUTE_ID=$VITE_INSTITUTE_ID
VITE_CODE_CIRCLE_INSTITUTE_ID=$VITE_CODE_CIRCLE_INSTITUTE_ID
VITE_HOLISTIC_INSTITUTE_ID=$VITE_HOLISTIC_INSTITUTE_ID

# Firebase (optional)
VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
EOF

echo "\n✅ Wrote .env at $ENV_FILE"
echo "You can now run 'pnpm dev' or 'npm run dev'."


