ALTER TABLE faculty_subject_package_session_mapping 
ADD COLUMN user_type VARCHAR(255) DEFAULT NULL,
ADD COLUMN type_id VARCHAR(255) DEFAULT NULL,
ADD COLUMN access_type VARCHAR(255) DEFAULT NULL,
ADD COLUMN access_id VARCHAR(255) DEFAULT NULL,
ADD COLUMN access_permission VARCHAR(255) DEFAULT NULL,
ADD COLUMN linkage_type VARCHAR(255) DEFAULT NULL,
ADD COLUMN suborg_id VARCHAR(255) DEFAULT NULL;

CREATE TABLE institute_suborg (
  id VARCHAR(255) NOT NULL,
  institute_id VARCHAR(255) DEFAULT NULL,
  suborg_id VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  status VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
