import React, { useState, useRef, useEffect } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Form, FormControl, FormField, FormItem } from "@/components/ui/form";
import { toast } from "sonner";
import { motion } from "framer-motion";
import { useMutation } from "@tanstack/react-query";
import axios from "axios";
import { useNavigate } from "@tanstack/react-router";
import { 
    Mail,
    Loader2,
    CheckCircle,
    ArrowLeft,
    RefreshCw,
} from "lucide-react";
import { MyInput } from "@/components/design-system/input";
import { Input } from "@/components/ui/input";
import { LIVE_SESSION_REQUEST_OTP, LIVE_SESSION_VERIFY_OTP, LOGIN_OTP, REQUEST_OTP } from "@/constants/urls";
import { getUserDetailsByEmail } from "@/services/signup-api";

const emailSchema = z.object({
    email: z.string().email("Please enter a valid email address"),
});

const otpSchema = z.object({
    otp: z.array(z.string().min(1, "Required")).length(6, "Please enter 6 digits"),
});

type EmailFormValues = z.infer<typeof emailSchema>;
type OtpFormValues = { otp: string[] };

interface SignupEmailOtpFormProps {
    onUserDetailsCheck: (userData: { email: string; response: unknown }) => void;
    onSwitchToLogin?: () => void;
    userExists?: boolean;
    onUserExistsChange?: (exists: boolean) => void;
    hideHeader?: boolean; // New prop to hide header when used in modal
}

export function SignupEmailOtpForm({
    onUserDetailsCheck,
    onSwitchToLogin,
    userExists: propUserExists,
    onUserExistsChange,
    hideHeader = false, // Default to false for backward compatibility
}: SignupEmailOtpFormProps) {
    const navigate = useNavigate();
    const [isOtpSent, setIsOtpSent] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [timer, setTimer] = useState(0);
    const [email, setEmail] = useState("");
    const [userExists, setUserExists] = useState(propUserExists || false);
    const timerRef = useRef<NodeJS.Timeout | null>(null);

    // Update local state when prop changes
    useEffect(() => {
        if (propUserExists !== undefined) {
            setUserExists(propUserExists);
        }
    }, [propUserExists]);

    // Notify parent when user existence changes
    const updateUserExists = (exists: boolean) => {
        setUserExists(exists);
        if (onUserExistsChange) {
            onUserExistsChange(exists);
        }
    };

    const emailForm = useForm<EmailFormValues>({
        resolver: zodResolver(emailSchema),
        defaultValues: {
            email: "",
        },
    });

    const otpForm = useForm<OtpFormValues>({
        resolver: zodResolver(otpSchema),
        defaultValues: {
            otp: ["", "", "", "", "", ""],
        },
    });

    // Timer effect with proper cleanup
    useEffect(() => {
        return () => {
            if (timerRef.current) clearInterval(timerRef.current);
        };
    }, []);

    const startTimer = () => {
        setTimer(60);
        if (timerRef.current) clearInterval(timerRef.current);

        timerRef.current = setInterval(() => {
            setTimer((prev) => {
                if (prev <= 1) {
                    clearInterval(timerRef.current!);
                    return 0;
                }
                return prev - 1;
            });
        }, 1000);
    };

    const handleBackToEmail = () => {
        setIsOtpSent(false);
        setTimer(0);
        updateUserExists(false);
        if (timerRef.current) clearInterval(timerRef.current);
        otpForm.reset();
    };

    const sendOtpMutation = useMutation({
        mutationFn: async (email: string) => {
            // First check if user exists
            let userExistsStatus = false;
            try {
                await getUserDetailsByEmail(email);
                userExistsStatus = true;
            } catch (error) {
                if (error instanceof Error && error.message === "USER_NOT_FOUND") {
                    userExistsStatus = false;
                } else {
                    // If there's an error checking user, assume user doesn't exist and continue with signup
                    userExistsStatus = false;
                }
            }

            // Update the state immediately
            updateUserExists(userExistsStatus);

            // Send OTP using the appropriate endpoint based on user existence
            const endpoint = userExistsStatus ? REQUEST_OTP : LIVE_SESSION_REQUEST_OTP;
            const payload = userExistsStatus 
                ? {
                    email: email,
                    service: "login"
                }
                : {
                    to: email,
                    subject: "Email Verification",
                    service: "signup",
                    name: "User",
                    otp: "" // OTP will be generated by the backend
                };

            return axios.post(endpoint, payload);
        },
        onMutate: () => {
            setIsLoading(true);
        },
        onSuccess: () => {
            setIsLoading(false);
            setIsOtpSent(true);
            startTimer();
            toast.success("OTP sent successfully");
        },
        onError: () => {
            setIsLoading(false);
            toast.error("Failed to send OTP", {
                description: "Please try again",
                duration: 3000,
            });
        },
    });

    const verifyOtpMutation = useMutation({
        mutationFn: (data: { email: string; otp: string }) => {
            // Use different endpoint based on whether user exists
            const endpoint = userExists ? LOGIN_OTP : LIVE_SESSION_VERIFY_OTP;
            
            return axios.post(endpoint, {
                to: data.email,
                subject: "Email Verification",
                service: userExists ? "login" : "signup",
                name: "User",
                otp: data.otp
            });
        },
        onSuccess: async (response) => {
            try {
                if (userExists) {
                    // User exists - handle login flow
                    // You might want to redirect to dashboard or handle login differently
                    toast.success("Login successful!");
                    // For now, just show success - you can customize this based on your login flow
                } else {
                    // User doesn't exist - continue with signup flow
                    onUserDetailsCheck({ email, response });
                }
            } catch (error) {
                console.error("Error in verification:", error);
                toast.error("Verification failed. Please try again.");
            }
        },
        onError: () => {
            toast.error("Invalid OTP", {
                description: "Please check your code and try again",
                duration: 3000,
            });
        },
    });

    const onEmailSubmit = (data: EmailFormValues) => {
        setEmail(data.email);
        sendOtpMutation.mutate(data.email);
    };

    const onOtpSubmit = () => {
        const otpValue = otpForm.getValues("otp").join("");
        if (otpValue.length === 6) {
            verifyOtpMutation.mutate({ email, otp: otpValue });
        }
    };

    const handleOtpPaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
        e.preventDefault();
        const pastedData = e.clipboardData.getData("text/plain").slice(0, 6);
        const otpArray = pastedData.split("").concat(Array(6 - pastedData.length).fill(""));
        otpForm.setValue("otp", otpArray);
        
        // Focus the next empty input or the last input
        const nextIndex = Math.min(pastedData.length, 5);
        const nextInput = document.querySelector(`input[name="otp.${nextIndex}"]`) as HTMLInputElement;
        if (nextInput) {
            nextInput.focus();
        }
    };

    const handleOtpChange = (element: HTMLInputElement, index: number) => {
        const value = element.value;
        if (value.length > 1) {
            element.value = value[0];
        }

        // Update form value
        const currentOtp = otpForm.getValues("otp");
        currentOtp[index] = value;
        otpForm.setValue("otp", currentOtp);

        // Move to next input if value is entered
        if (value && index < 5) {
            const nextInput = document.querySelector(
                `input[name="otp.${index + 1}"]`
            ) as HTMLInputElement;
            if (nextInput) {
                nextInput.focus();
            }
        }
    };

    const handleOtpKeyDown = (
        e: React.KeyboardEvent<HTMLInputElement>,
        index: number
    ) => {
        if (e.key === "Backspace" && !e.currentTarget.value && index > 0) {
            const prevInput = document.querySelector(
                `input[name="otp.${index - 1}"]`
            ) as HTMLInputElement;
            if (prevInput) {
                prevInput.focus();
            }
        }
    };

    return (
        <div className="space-y-6">
            {!isOtpSent ? (
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    className="space-y-4"
                >
                    {/* Conditional Header based on user existence - only show if not hidden */}
                    {!hideHeader && (
                        <>
                            {userExists ? (
                                <motion.div
                                    initial={{ y: 10, opacity: 0 }}
                                    animate={{ y: 0, opacity: 1 }}
                                    transition={{ delay: 0.1 }}
                                    className="text-center space-y-3"
                                >
                                    <div className="space-y-1">
                                        <h3 className="text-lg font-semibold text-gray-900">
                                            Welcome Back
                                        </h3>
                                        <p className="text-sm text-gray-600">
                                            Sign in to continue your learning journey
                                        </p>
                                    </div>
                                </motion.div>
                            ) : (
                                <motion.div
                                    initial={{ y: 10, opacity: 0 }}
                                    animate={{ y: 0, opacity: 1 }}
                                    transition={{ delay: 0.1 }}
                                    className="text-center space-y-3"
                                >
                                    <div className="space-y-1">
                                        <h3 className="text-lg font-semibold text-gray-900">
                                            Create Your Account
                                        </h3>
                                        <p className="text-sm text-gray-600">
                                            Join our learning community and start your journey
                                        </p>
                                    </div>
                                </motion.div>
                            )}
                        </>
                    )}

                    <Form {...emailForm}>
                        <form onSubmit={emailForm.handleSubmit(onEmailSubmit)} className="space-y-4">
                            <FormField
                                control={emailForm.control}
                                name="email"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormControl>
                                            <div className="relative">
                                                <MyInput
                                                    inputType="email"
                                                    inputPlaceholder="Enter your email address"
                                                    label="Email Address"
                                                    required
                                                    size="large"
                                                    error={emailForm.formState.errors.email?.message}
                                                    className="w-full min-w-full transition-all duration-200 border-gray-200 focus:border-gray-300 focus:ring-0 focus-visible:ring-0 rounded-lg bg-gray-50/50 focus:bg-white hover:bg-white font-normal pr-10"
                                                    input={field.value}
                                                    onChangeFunction={field.onChange}
                                                />
                                                {/* Removed email icon per requirement */}
                                            </div>
                                        </FormControl>
                                    </FormItem>
                                )}
                            />

                            <motion.button
                                type="submit"
                                whileHover={{ scale: 1.01 }}
                                whileTap={{ scale: 0.99 }}
                                disabled={isLoading}
                                className="w-full bg-gray-900 hover:bg-black text-white font-medium py-3 px-4 rounded-lg transition-all duration-200 shadow-sm hover:shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <div className="flex items-center justify-center space-x-2">
                                    {isLoading ? (
                                        <Loader2 className="w-4 h-4 animate-spin" />
                                    ) : (
                                        <Mail className="w-4 h-4" />
                                    )}
                                    <span className="text-sm">
                                        {isLoading ? "Sending OTP..." : "Send OTP"}
                                    </span>
                                </div>
                            </motion.button>
                        </form>
                    </Form>
                    <motion.div
                        initial={{ y: 10, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ delay: 0.8 }}
                        className="text-center text-xs text-gray-500"
                    >
                        {userExists ? (
                            <>
                                Don't have an account?{" "}
                                <motion.button
                                    type="button"
                                    whileHover={{ scale: 1.02 }}
                                    onClick={() => {
                                        if (onSwitchToLogin) {
                                            onSwitchToLogin();
                                        } else {
                                            navigate({ to: "/signup" });
                                        }
                                    }}
                                    className="text-gray-700 hover:text-gray-900 font-medium underline cursor-pointer"
                                >
                                    Sign up here
                                </motion.button>
                            </>
                        ) : (
                            <>
                                Already have an account?{" "}
                                <motion.button
                                    type="button"
                                    whileHover={{ scale: 1.02 }}
                                    onClick={() => {
                                        if (onSwitchToLogin) {
                                            onSwitchToLogin();
                                        } else {
                                            navigate({ to: "/login" });
                                        }
                                    }}
                                    className="text-gray-700 hover:text-gray-900 font-medium underline cursor-pointer"
                                >
                                    Sign in here
                                </motion.button>
                            </>
                        )}
                    </motion.div>
                 </motion.div>
            ) : (
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    className="space-y-4"
                >
                    <div className="text-center space-y-2">
                        <div className="flex justify-center mb-2">
                            <Mail className="w-12 h-12 text-gray-600" />
                        </div>
                        <h3 className="text-lg font-semibold text-gray-900">
                            Enter Verification Code
                        </h3>
                        <p className="text-sm text-gray-600">
                            We've sent a 6-digit code to
                        </p>
                        <div className="flex justify-center mt-2">
                            <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-gray-100 text-gray-800 border border-gray-200">
                                <CheckCircle className="w-3 h-3 mr-1" />
                                {email}
                            </span>
                        </div>
                    </div>

                    <Form {...otpForm}>
                        <form
                            onSubmit={otpForm.handleSubmit(onOtpSubmit)}
                            className="space-y-4"
                        >
                            <motion.div
                                initial={{ y: 10, opacity: 0 }}
                                animate={{ y: 0, opacity: 1 }}
                                transition={{ delay: 0.4 }}
                                className="space-y-3"
                            >
                                <div className="flex justify-center gap-2">
                                    {[0, 1, 2, 3, 4, 5].map((index) => (
                                        <motion.div
                                            key={index}
                                            initial={{
                                                scale: 0,
                                                opacity: 0,
                                            }}
                                            animate={{
                                                scale: 1,
                                                opacity: 1,
                                            }}
                                            transition={{
                                                delay: 0.5 + index * 0.03,
                                            }}
                                        >
                                            <FormField
                                                control={otpForm.control}
                                                name={`otp.${index}`}
                                                render={({ field }) => (
                                                    <FormItem>
                                                        <FormControl>
                                                            <Input
                                                                {...field}
                                                                type="text"
                                                                inputMode="numeric"
                                                                maxLength={1}
                                                                className="h-12 w-12 text-center text-lg font-semibold border border-gray-200 rounded-lg transition-all duration-200 focus:border-gray-400 focus:ring-2 focus:ring-gray-100 hover:border-gray-300 bg-white shadow-sm"
                                                                onChange={(e) =>
                                                                    handleOtpChange(e.target, index)
                                                                }
                                                                onKeyDown={(e) =>
                                                                    handleOtpKeyDown(e, index)
                                                                }
                                                                onPaste={handleOtpPaste}
                                                            />
                                                        </FormControl>
                                                    </FormItem>
                                                )}
                                            />
                                        </motion.div>
                                    ))}
                                </div>
                                {otpForm.formState.errors.otp && (
                                    <p className="text-sm text-red-600">
                                        {otpForm.formState.errors.otp.message}
                                    </p>
                                )}
                            </motion.div>

                            <motion.button
                                type="submit"
                                whileHover={{ scale: 1.01 }}
                                whileTap={{ scale: 0.99 }}
                                disabled={verifyOtpMutation.isPending}
                                className="w-full bg-gray-900 hover:bg-black text-white font-medium py-3 px-4 rounded-lg transition-all duration-200 shadow-sm hover:shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <div className="flex items-center justify-center space-x-2">
                                    {verifyOtpMutation.isPending ? (
                                        <Loader2 className="w-4 h-4 animate-spin" />
                                    ) : (
                                        <CheckCircle className="w-4 h-4" />
                                    )}
                                    <span className="text-sm">
                                        {verifyOtpMutation.isPending 
                                            ? (userExists ? "Signing in..." : "Verifying...") 
                                            : (userExists ? "Sign In" : "Verify OTP")
                                        }
                                    </span>
                                </div>
                            </motion.button>

                            {/* Back button and Resend timer */}
                            <div className="flex justify-center items-center space-x-3 text-sm">
                                <motion.button
                                    type="button"
                                    onClick={handleBackToEmail}
                                    whileHover={{ scale: 1.02 }}
                                    whileTap={{ scale: 0.98 }}
                                    className="flex items-center space-x-1 text-gray-500 hover:text-gray-700 transition-colors duration-200 font-medium"
                                >
                                    <ArrowLeft className="w-3 h-3" />
                                    <span className="text-xs">
                                        Back to email
                                    </span>
                                </motion.button>

                                <div className="w-px h-3 bg-gray-300"></div>

                                <motion.button
                                    type="button"
                                    whileHover={
                                        timer === 0
                                            ? { scale: 1.02 }
                                            : {}
                                    }
                                    whileTap={
                                        timer === 0
                                            ? { scale: 0.98 }
                                            : {}
                                    }
                                    className={`transition-colors duration-200 font-medium ${
                                        timer > 0
                                            ? "text-gray-400 cursor-not-allowed"
                                            : "text-gray-700 hover:text-gray-900"
                                    }`}
                                    onClick={() =>
                                        timer === 0 &&
                                        sendOtpMutation.mutate(email)
                                    }
                                    disabled={timer > 0}
                                >
                                    {timer > 0 ? (
                                        <div className="flex items-center space-x-1">
                                            <RefreshCw className="w-3 h-3" />
                                            <span className="text-xs">
                                                Resend in {timer}s
                                            </span>
                                        </div>
                                    ) : (
                                        <div className="flex items-center space-x-1">
                                            <RefreshCw className="w-3 h-3" />
                                            <span className="text-xs">
                                                Resend code
                                            </span>
                                        </div>
                                    )}
                                </motion.button>
                            </div>
                        </form>
                    </Form>
                    <motion.div
                        initial={{ y: 10, opacity: 0 }}
                        animate={{ y: 0, opacity: 1 }}
                        transition={{ delay: 0.8 }}
                        className="text-center text-xs text-gray-500"
                    >
                        {userExists ? (
                            <motion.button
                                type="button"
                                whileHover={{ scale: 1.02 }}
                                onClick={() => {
                                    if (onSwitchToLogin) {
                                        onSwitchToLogin();
                                    } else {
                                        navigate({ to: "/login" });
                                    }
                                }}
                                className="text-gray-700 hover:text-gray-900 font-medium underline cursor-pointer"
                            >
                                Sign in here
                            </motion.button>
                        ) : (
                            <motion.button
                                type="button"
                                whileHover={{ scale: 1.02 }}
                                onClick={() => {
                                    if (onSwitchToLogin) {
                                        onSwitchToLogin();
                                    } else {
                                        navigate({ to: "/login" });
                                    }
                                }}
                                className="text-gray-700 hover:text-gray-900 font-medium underline cursor-pointer"
                            >
                                Sign in here
                            </motion.button>
                        )}
                    </motion.div>
                 </motion.div>
             )}
         </div>
     );
} 