CREATE TABLE IF NOT EXISTS backend_base_url (
    id VARCHAR(255) PRIMARY KEY,
    institute_id VARCHAR(255) NOT NULL UNIQUE,
    base_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);