package vacademy.io.admin_core_service.features.workflow.dto.execution_log;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * Execution details for TRIGGER node.
 * Captures output data points generated by the trigger.
 */
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TriggerNodeExecutionDetails extends BaseNodeExecutionDetails {

    private List<OutputDataPoint> outputDataPoints;
    private List<String> evaluationErrors;
    private Integer dataPoints;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class OutputDataPoint {
        private String fieldName;
        private Object value;
        private String computeExpression;
        private Boolean evaluationSuccess;
        private String evaluationError;
    }
}
