export const titleSlide = [
                {
                    id: "wNqRSSHVbW9uplUfC3oEq",
                    type: "rectangle",
                    x: 432.5,
                    y: 84.08984375,
                    width: 338.4765625,
                    height: 56.34765624999999,
                    angle: 0,
                    strokeColor: "#1e1e1e",
                    backgroundColor: "transparent",
                    fillStyle: "solid",
                    strokeWidth: 2,
                    strokeStyle: "solid",
                    roughness: 1,
                    opacity: 100,
                    groupIds: [],
                    frameId: null,
                    index: "a6",
                    roundness: null,
                    seed: 832054520,
                    version: 356,
                    versionNonce: 1287233272,
                    isDeleted: false,
                    boundElements: [
                        {
                            type: "text",
                            id: "GVrorLQ-Uz4wNLLykDLo-"
                        }
                    ],
                    updated: 1742913654413,
                    link: null,
                    locked: false
                },
                {
                    id: "GVrorLQ-Uz4wNLLykDLo-",
                    type: "text",
                    x: 465.279296875,
                    y: 89.763671875,
                    width: 272.91796875,
                    height: 45,
                    angle: 0,
                    strokeColor: "#1e1e1e",
                    backgroundColor: "transparent",
                    fillStyle: "solid",
                    strokeWidth: 2,
                    strokeStyle: "solid",
                    roughness: 1,
                    opacity: 100,
                    groupIds: [],
                    frameId: null,
                    index: "a7",
                    roundness: null,
                    seed: 34860536,
                    version: 152,
                    versionNonce: 186318840,
                    isDeleted: false,
                    boundElements: [],
                    updated: 1742913654413,
                    link: null,
                    locked: false,
                    text: "Add your title here",
                    fontSize: 36,
                    fontFamily: 5,
                    textAlign: "center",
                    verticalAlign: "middle",
                    containerId: "wNqRSSHVbW9uplUfC3oEq",
                    originalText: "Add your title here",
                    autoResize: true,
                    lineHeight: 1.25
                }
]

export const textSlide = [
        {
            "id": "Ddoxcl6FZdGu6PnlBlhMH",
            "type": "text",
            "x": 458.73828125,
            "y": 41.5625,
            "width": 216.66796875,
            "height": 48.6,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a1",
            "roundness": null,
            "seed": 1420285362,
            "version": 90,
            "versionNonce": 806972082,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742919728871,
            "link": null,
            "locked": false,
            "text": "Add Title Here",
            "fontSize": 36,
            "fontFamily": 6,
            "textAlign": "left",
            "verticalAlign": "top",
            "containerId": null,
            "originalText": "Add Title Here",
            "autoResize": true,
            "lineHeight": 1.35
        },
        {
            "id": "ESkETxNe_j_S3aYS4aQWJ",
            "type": "text",
            "x": 105.015625,
            "y": 203.64609375,
            "width": 247.255859375,
            "height": 37.800000000000004,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a2",
            "roundness": null,
            "seed": 2060337266,
            "version": 109,
            "versionNonce": 1653100530,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742919731170,
            "link": null,
            "locked": false,
            "text": "Add Description Here",
            "fontSize": 28,
            "fontFamily": 6,
            "textAlign": "left",
            "verticalAlign": "top",
            "containerId": null,
            "originalText": "Add Description Here",
            "autoResize": true,
            "lineHeight": 1.35
        }
]

export const webEmbedSlide = [
        {
            "id": "HqmuibhdvBgGuwqOX8r0t",
            "type": "embeddable",
            "x": 101.23828125,
            "y": 99.546875,
            "width": 975.5078125,
            "height": 507.64453125,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a0",
            "roundness": {
                "type": 3
            },
            "seed": 2024164078,
            "version": 87,
            "versionNonce": 1230021422,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742919904259,
            "link": null,
            "locked": false
        }
]

export const textMediaSlide = [
        {
            "id": "pfSykSLyHLYLydP_c9qX6",
            "type": "rectangle",
            "x": 295.171875,
            "y": 70.94140625,
            "width": 477.8828125,
            "height": 71.203125,
            "angle": 0,
            "strokeColor": "#f08c00",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 4,
            "strokeStyle": "solid",
            "roughness": 0,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a2",
            "roundness": {
                "type": 3
            },
            "seed": 28275442,
            "version": 199,
            "versionNonce": 1205771826,
            "isDeleted": false,
            "boundElements": [
                {
                    "type": "text",
                    "id": "jdnu6xe85ulq2RTqQNFoI"
                }
            ],
            "updated": 1742920756875,
            "link": null,
            "locked": false
        },
        {
            "id": "jdnu6xe85ulq2RTqQNFoI",
            "type": "text",
            "x": 403.6484375,
            "y": 84.04296875,
            "width": 260.9296875,
            "height": 45,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a2G",
            "roundness": null,
            "seed": 332703794,
            "version": 97,
            "versionNonce": 1854932978,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742920756875,
            "link": null,
            "locked": false,
            "text": "Add you title here",
            "fontSize": 36,
            "fontFamily": 7,
            "textAlign": "center",
            "verticalAlign": "middle",
            "containerId": "pfSykSLyHLYLydP_c9qX6",
            "originalText": "Add you title here",
            "autoResize": true,
            "lineHeight": 1.15
        },
        {
            "id": "lLTOtNOdvFjJIabuR72CD",
            "type": "text",
            "x": 394.88671875,
            "y": 203.765625,
            "width": 295.498046875,
            "height": 25,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 4,
            "strokeStyle": "solid",
            "roughness": 0,
            "opacity": 80,
            "groupIds": [],
            "frameId": null,
            "index": "a7",
            "roundness": null,
            "seed": 1268999538,
            "version": 141,
            "versionNonce": 863230322,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742920759776,
            "link": null,
            "locked": false,
            "text": "Press 9 on keyboard to upload image",
            "fontSize": 20,
            "fontFamily": 5,
            "textAlign": "center",
            "verticalAlign": "top",
            "containerId": null,
            "originalText": "Press 9 on keyboard to upload image",
            "autoResize": true,
            "lineHeight": 1.25
        }
]

export const videoSlide = [
        {
            "id": "4DslH9D3qllWCm_sSNHDx",
            "type": "embeddable",
            "x": 570.67578125,
            "y": 181.828125,
            "width": 596.86328125,
            "height": 333.99169921875,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a1",
            "roundness": null,
            "seed": 1864555826,
            "version": 226,
            "versionNonce": 51105198,
            "isDeleted": false,
            "boundElements": [
                {
                    "id": "jj5kHRLqdYvad1dS19z5q",
                    "type": "arrow"
                }
            ],
            "updated": 1742920257077,
            "link": "https://youtu.be/5Nih_ygV-18?feature=shared",
            "locked": false
        },
        {
            "id": "DFumUc6CT3gw-fMDXGfdy",
            "type": "text",
            "x": 137.62109375,
            "y": 62.18359375,
            "width": 259.7109375,
            "height": 35,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 50,
            "groupIds": [],
            "frameId": null,
            "index": "a2",
            "roundness": null,
            "seed": 1925263922,
            "version": 179,
            "versionNonce": 1337813170,
            "isDeleted": false,
            "boundElements": [
                {
                    "id": "jj5kHRLqdYvad1dS19z5q",
                    "type": "arrow"
                }
            ],
            "updated": 1742920260799,
            "link": null,
            "locked": false,
            "text": "Add you video url here",
            "fontSize": 28,
            "fontFamily": 5,
            "textAlign": "left",
            "verticalAlign": "top",
            "containerId": null,
            "originalText": "Add you video url here",
            "autoResize": true,
            "lineHeight": 1.25
        },
        {
            "id": "jj5kHRLqdYvad1dS19z5q",
            "type": "arrow",
            "x": 412.765625,
            "y": 79.20703125,
            "width": 206.64294752543583,
            "height": 80.67714541580077,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "dashed",
            "roughness": 1,
            "opacity": 40,
            "groupIds": [],
            "frameId": null,
            "index": "a3",
            "roundness": {
                "type": 2
            },
            "seed": 2073904114,
            "version": 438,
            "versionNonce": 209552626,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742920262414,
            "link": null,
            "locked": false,
            "points": [
                [
                    0,
                    0
                ],
                [
                    150.52005119359274,
                    11.164970514983546
                ],
                [
                    206.64294752543583,
                    80.67714541580077
                ]
            ],
            "lastCommittedPoint": null,
            "startBinding": {
                "elementId": "DFumUc6CT3gw-fMDXGfdy",
                "focus": -0.41476688159058145,
                "gap": 15.43359375
            },
            "endBinding": {
                "elementId": "4DslH9D3qllWCm_sSNHDx",
                "focus": -0.22423477195596514,
                "gap": 21.943948334199234
            },
            "startArrowhead": null,
            "endArrowhead": "arrow",
            "elbowed": false
        }
]

export const fullMediaSlide = [
        {
            "id": "OVfFjor3L_vUuQf-swzr3",
            "type": "embeddable",
            "x": 33.41015625,
            "y": 96.12109375,
            "width": 1146.17578125,
            "height": 575.384033203125,
            "angle": 0,
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 2,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "frameId": null,
            "index": "a0",
            "roundness": {
                "type": 3
            },
            "seed": 1906330926,
            "version": 229,
            "versionNonce": 1533977778,
            "isDeleted": false,
            "boundElements": null,
            "updated": 1742920885956,
            "link": "https://youtu.be/5Nih_ygV-18?feature=shared",
            "locked": false
        }
]