blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/Vacademy-io/vacademy_platform/discussions
    about: Please use GitHub Discussions for questions, help requests, and general conversations.
