// ─────────────────────────────────────────────────────────────
// Mock data for Parent Portal demo/preview
// ─────────────────────────────────────────────────────────────

import type {
  ChildProfile,
  AdmissionOverview,
  AdmissionTimelineEvent,
  RegistrationFormData,
  InterviewSchedule,
  AssessmentSchedule,
  PaymentSummary,
  PaymentHistory,
  DocumentsResponse,
} from "@/types/parent-portal";

export const MOCK_CHILDREN: ChildProfile[] = [
  {
    id: "child-1",
    full_name: "Aarav Sharma",
    date_of_birth: "2016-03-15",
    gender: "MALE",
    grade_applying: "Grade 4",
    academic_year: "2026-27",
    admission_status: "REGISTRATION_IN_PROGRESS",
    inquiry_id: "inq-001",
    avatar_file_id: "",
    batch_name: "",
    created_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "child-2",
    full_name: "Ananya Sharma",
    date_of_birth: "2019-07-22",
    gender: "FEMALE",
    grade_applying: "Grade 1",
    academic_year: "2026-27",
    admission_status: "INQUIRY_SUBMITTED",
    inquiry_id: "inq-002",
    avatar_file_id: "",
    batch_name: "",
    created_at: "2026-01-15T14:30:00Z",
  },
];

export const MOCK_OVERVIEW: AdmissionOverview = {
  child_id: "child-1",
  current_status: "REGISTRATION_IN_PROGRESS",
  next_action: "Complete and submit your registration form",
  progress_percentage: 35,
  timeline: [
    {
      id: "evt-1",
      title: "Inquiry Submitted",
      description: "Initial inquiry form submitted online",
      status: "COMPLETED",
      timestamp: "2026-01-10T10:00:00Z",
    },
    {
      id: "evt-2",
      title: "Inquiry Reviewed",
      description: "Your inquiry has been reviewed by the admissions committee",
      status: "COMPLETED",
      timestamp: "2026-01-12T15:30:00Z",
    },
    {
      id: "evt-3",
      title: "Registration Opened",
      description: "You can now fill the registration form",
      status: "COMPLETED",
      timestamp: "2026-01-14T09:00:00Z",
    },
    {
      id: "evt-4",
      title: "Registration Form",
      description: "Complete all sections of the registration form",
      status: "CURRENT",
      timestamp: "",
    },
  ],
};

export const MOCK_TIMELINE: AdmissionTimelineEvent[] = [
  {
    id: "tl-1",
    title: "Inquiry Submitted",
    description: "Online inquiry form submitted with student details",
    status: "COMPLETED",
    timestamp: "2026-01-10T10:00:00Z",
  },
  {
    id: "tl-2",
    title: "Inquiry Reviewed",
    description: "Admissions team reviewed and approved the inquiry",
    status: "COMPLETED",
    timestamp: "2026-01-12T15:30:00Z",
  },
  {
    id: "tl-3",
    title: "Registration Opened",
    description: "Registration form is now available for completion",
    status: "COMPLETED",
    timestamp: "2026-01-14T09:00:00Z",
  },
  {
    id: "tl-4",
    title: "Registration Form Submission",
    description: "Fill all sections and submit the registration form",
    status: "CURRENT",
    timestamp: "",
  },
  {
    id: "tl-5",
    title: "Interview & Assessment",
    description: "Attend the scheduled interview and entrance test",
    status: "UPCOMING",
    timestamp: "",
  },
  {
    id: "tl-6",
    title: "Fee Payment",
    description: "Pay the admission and tuition fees",
    status: "UPCOMING",
    timestamp: "",
  },
  {
    id: "tl-7",
    title: "Document Verification",
    description: "Submit and get all required documents verified",
    status: "UPCOMING",
    timestamp: "",
  },
  {
    id: "tl-8",
    title: "Enrollment Complete",
    description: "Welcome aboard!",
    status: "UPCOMING",
    timestamp: "",
  },
];

export const MOCK_REGISTRATION: RegistrationFormData = {
  id: "form-1",
  title: "Student Registration Form",
  description: "Please fill all sections carefully",
  status: "IN_PROGRESS",
  sections: [
    {
      id: "sec-1",
      title: "Student Details",
      description: "Basic information about the student",
      order: 1,
      fields: [
        {
          id: "f1",
          label: "Full Name",
          type: "text",
          is_required: true,
          placeholder: "Enter student's full name",
          value: "Aarav Sharma",
        },
        {
          id: "f2",
          label: "Date of Birth",
          type: "date",
          is_required: true,
          value: "2016-03-15",
        },
        {
          id: "f3",
          label: "Gender",
          type: "select",
          is_required: true,
          options: ["Male", "Female", "Other"],
          value: "Male",
        },
        {
          id: "f4",
          label: "Blood Group",
          type: "select",
          is_required: false,
          options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
          value: "",
        },
        {
          id: "f5",
          label: "Aadhaar Number",
          type: "text",
          is_required: false,
          placeholder: "12 digit Aadhaar number",
          value: "",
        },
      ],
    },
    {
      id: "sec-2",
      title: "Parent/Guardian Details",
      description: "Information about the parent or guardian",
      order: 2,
      fields: [
        {
          id: "f6",
          label: "Father's Name",
          type: "text",
          is_required: true,
          placeholder: "Enter father's full name",
          value: "",
        },
        {
          id: "f7",
          label: "Father's Occupation",
          type: "text",
          is_required: false,
          placeholder: "Enter occupation",
          value: "",
        },
        {
          id: "f8",
          label: "Mother's Name",
          type: "text",
          is_required: true,
          placeholder: "Enter mother's full name",
          value: "",
        },
        {
          id: "f9",
          label: "Contact Number",
          type: "text",
          is_required: true,
          placeholder: "+91 XXXXX XXXXX",
          value: "",
        },
        {
          id: "f10",
          label: "Email Address",
          type: "email",
          is_required: true,
          placeholder: "parent@email.com",
          value: "",
        },
      ],
    },
    {
      id: "sec-3",
      title: "Address Information",
      description: "Current residential address",
      order: 3,
      fields: [
        {
          id: "f11",
          label: "Address Line 1",
          type: "text",
          is_required: true,
          placeholder: "House/Flat number, Street",
          value: "",
        },
        {
          id: "f12",
          label: "City",
          type: "text",
          is_required: true,
          placeholder: "City name",
          value: "",
        },
        {
          id: "f13",
          label: "State",
          type: "text",
          is_required: true,
          placeholder: "State",
          value: "",
        },
        {
          id: "f14",
          label: "PIN Code",
          type: "text",
          is_required: true,
          placeholder: "6 digit PIN code",
          value: "",
        },
      ],
    },
    {
      id: "sec-4",
      title: "Previous Academics",
      description: "Details of previous school attended",
      order: 4,
      fields: [
        {
          id: "f15",
          label: "Previous School Name",
          type: "text",
          is_required: false,
          placeholder: "Enter school name",
          value: "",
        },
        {
          id: "f16",
          label: "Last Class Attended",
          type: "text",
          is_required: false,
          placeholder: "e.g. Grade 3",
          value: "",
        },
        {
          id: "f17",
          label: "Reason for Leaving",
          type: "textarea",
          is_required: false,
          placeholder: "Brief reason",
          value: "",
        },
      ],
    },
  ],
};

export const MOCK_INTERVIEW: InterviewSchedule = {
  id: "int-1",
  scheduled_date: "2026-02-20",
  scheduled_time: "10:00 AM",
  duration_minutes: 30,
  mode: "ONLINE",
  meeting_link: "https://meet.google.com/abc-defg-hij",
  status: "SCHEDULED",
  location: "",
};

export const MOCK_ASSESSMENT: AssessmentSchedule = {
  id: "asm-1",
  scheduled_date: "2026-02-22",
  scheduled_time: "11:00 AM",
  duration_minutes: 60,
  mode: "OFFLINE",
  location: "School Campus, Room 204",
  status: "SCHEDULED",
};

export const MOCK_PAYMENT_SUMMARY: PaymentSummary = {
  child_id: "child-1",
  currency: "₹",
  total_fees: 85000,
  total_paid: 15000,
  total_pending: 70000,
  total_overdue: 15000,
  fee_items: [
    {
      id: "fee-1",
      category: "REGISTRATION",
      description: "Registration Fee",
      amount: 5000,
      discount: 0,
      total: 5000,
      status: "COMPLETED",
      due_date: "2026-01-20",
    },
    {
      id: "fee-2",
      category: "ADMISSION",
      description: "Admission Fee",
      amount: 15000,
      discount: 1000,
      total: 14000,
      status: "OVERDUE",
      due_date: "2026-02-01",
    },
    {
      id: "fee-3",
      category: "TUITION",
      description: "Tuition Fee (Term 1)",
      amount: 35000,
      discount: 0,
      total: 35000,
      status: "PENDING",
      due_date: "2026-03-15",
    },
    {
      id: "fee-4",
      category: "TRANSPORT",
      description: "Transport Fee (Annual)",
      amount: 18000,
      discount: 0,
      total: 18000,
      status: "PENDING",
      due_date: "2026-03-15",
    },
    {
      id: "fee-5",
      category: "LIBRARY",
      description: "Library & Lab Fee",
      amount: 3000,
      discount: 0,
      total: 3000,
      status: "PENDING",
      due_date: "2026-03-15",
    },
    {
      id: "fee-6",
      category: "ADDITIONAL",
      description: "Annual Sports Fee",
      amount: 10000,
      discount: 0,
      total: 10000,
      status: "COMPLETED",
      due_date: "2026-01-20",
    },
  ],
};

export const MOCK_PAYMENT_HISTORY: PaymentHistory = {
  child_id: "child-1",
  transactions: [
    {
      id: "txn-1",
      amount: 5000,
      currency: "₹",
      status: "SUCCESS",
      payment_method: "UPI",
      transaction_ref: "UPI-20260120-001",
      paid_at: "2026-01-20T11:30:00Z",
    },
    {
      id: "txn-2",
      amount: 10000,
      currency: "₹",
      status: "SUCCESS",
      payment_method: "Net Banking",
      transaction_ref: "NB-20260120-002",
      paid_at: "2026-01-20T11:35:00Z",
    },
  ],
};

export const MOCK_DOCUMENTS: DocumentsResponse = {
  child_id: "child-1",
  total_required: 5,
  total_uploaded: 3,
  total_approved: 1,
  total_rejected: 1,
  documents: [
    {
      id: "doc-1",
      document_name: "Birth Certificate",
      description: "Original or certified copy of birth certificate",
      is_required: true,
      allowed_formats: ["pdf", "jpg", "png"],
      max_size_mb: 5,
      status: "APPROVED",
      uploaded_file_name: "aarav_birth_certificate.pdf",
      uploaded_at: "2026-01-18T10:00:00Z",
    },
    {
      id: "doc-2",
      document_name: "Previous School TC",
      description: "Transfer certificate from the last attended school",
      is_required: true,
      allowed_formats: ["pdf"],
      max_size_mb: 5,
      status: "UNDER_REVIEW",
      uploaded_file_name: "transfer_cert.pdf",
      uploaded_at: "2026-02-01T09:30:00Z",
    },
    {
      id: "doc-3",
      document_name: "Passport Size Photos",
      description: "Two recent passport size photographs",
      is_required: true,
      allowed_formats: ["jpg", "png"],
      max_size_mb: 2,
      status: "REJECTED",
      uploaded_file_name: "photo_aarav.jpg",
      uploaded_at: "2026-01-20T08:00:00Z",
      rejection_reason:
        "Photo is blurry. Please upload a clear, recent photograph with white background.",
    },
    {
      id: "doc-4",
      document_name: "Aadhaar Card (Student)",
      description: "Copy of student's Aadhaar card",
      is_required: true,
      allowed_formats: ["pdf", "jpg", "png"],
      max_size_mb: 5,
      status: "NOT_UPLOADED",
    },
    {
      id: "doc-5",
      document_name: "Previous Report Card",
      description: "Last year's report card or marksheet",
      is_required: false,
      allowed_formats: ["pdf", "jpg", "png"],
      max_size_mb: 5,
      status: "NOT_UPLOADED",
    },
  ],
};
