apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-core-service
  namespace: default
  labels:
    app: admin-core-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: admin-core-service
  template:
    metadata:
      labels:
        app: admin-core-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: admin-core-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: admin-core-service
          image: "public.ecr.aws/h3e7x6t4/admin-core-service/admin-core-service-repo:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: myconfigmapv1.0
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /admin-core-service/actuator/health
              port: 8072
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /admin-core-service/actuator/health
              port: 8072
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /admin-core-service/actuator/health
              port: 8072
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: 8072
