apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
  namespace: default
  labels:
    app: assessment-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: assessment-service
  template:
    metadata:
      labels:
        app: assessment-service
    spec:
      containers:
        - name: assessment-service
          image: "public.ecr.aws/h3e7x6t4/assessment-service/assessment-service-repo:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1536Mi"
          livenessProbe:
            httpGet:
              path: /assessment-service/actuator/health
              port: 8074
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /assessment-service/actuator/health
              port: 8074
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /assessment-service/actuator/health
              port: 8074
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: 8074
