apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "public.ecr.aws/h3e7x6t4/auth-service/auth-service-repo:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "768Mi"
            limits:
              cpu: "750m"
              memory: "1536Mi"
          livenessProbe:
            httpGet:
              path: /auth-service/actuator/health
              port: 8071
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /auth-service/actuator/health
              port: 8071
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /auth-service/actuator/health
              port: 8071
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: 8071
