apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: default
  labels:
    app: media-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: "public.ecr.aws/h3e7x6t4/media-service/media-service-repo:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /media-service/actuator/health
              port: 8075
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /media-service/actuator/health
              port: 8075
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /media-service/actuator/health
              port: 8075
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: 8075
