export const questionsCompleteResponseData = {
    questions: [
        {
            id: null,
            preview_id: null,
            section_id: null,
            question_order_in_section: null,
            text: {
                id: null,
                type: "HTML",
                content: "Which one of the following is a polynomial? ",
            },
            media_id: null,
            created_at: null,
            updated_at: null,
            question_response_type: "OPTION",
            question_type: "MCQS",
            access_level: "PUBLIC",
            auto_evaluation_json: '{"type":"MCQS","data":null}',
            options_json: null,
            parsed_evaluation_object: null,
            evaluation_type: null,
            explanation_text: {
                id: null,
                type: "HTML",
                content: "",
            },
            default_question_time_mins: null,
            parent_rich_text_id: null,
            parent_rich_text: null,
            options: [
                {
                    id: null,
                    preview_id: "0",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "first option",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "1",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "second option",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "2",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "third option",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "3",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "fourth option",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
            ],
            errors: [],
            warnings: [],
            tags: ["polynomial"],
            level: "easy",
        },
        {
            id: null,
            preview_id: null,
            section_id: null,
            question_order_in_section: null,
            text: {
                id: null,
                type: "HTML",
                content: "",
            },
            media_id: null,
            created_at: null,
            updated_at: null,
            question_response_type: "OPTION",
            question_type: "MCQS",
            access_level: "PUBLIC",
            auto_evaluation_json: '{"type":"MCQS","data":null}',
            options_json: null,
            parsed_evaluation_object: null,
            evaluation_type: null,
            explanation_text: {
                id: null,
                type: "HTML",
                content: "",
            },
            default_question_time_mins: null,
            parent_rich_text_id: null,
            parent_rich_text: null,
            options: [
                {
                    id: null,
                    preview_id: "0",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "2",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "1",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "0",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "2",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "1",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "3",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
            ],
            errors: [],
            warnings: [],
            tags: ["polynomial", "degree"],
            level: "easy",
        },
        {
            id: null,
            preview_id: null,
            section_id: null,
            question_order_in_section: null,
            text: {
                id: null,
                type: "HTML",
                content: "Degree of the polynomial 7",
            },
            media_id: null,
            created_at: null,
            updated_at: null,
            question_response_type: "OPTION",
            question_type: "MCQS",
            access_level: "PUBLIC",
            auto_evaluation_json: '{"type":"MCQS","data":null}',
            options_json: null,
            parsed_evaluation_object: null,
            evaluation_type: null,
            explanation_text: {
                id: null,
                type: "HTML",
                content: "Degree ",
            },
            default_question_time_mins: null,
            parent_rich_text_id: null,
            parent_rich_text: null,
            options: [
                {
                    id: null,
                    preview_id: "0",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "4",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "1",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "5",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "2",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "3",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "3",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "7",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
            ],
            errors: [],
            warnings: [],
            tags: ["polynomial", "degree"],
            level: "easy",
        },
        {
            id: null,
            preview_id: null,
            section_id: null,
            question_order_in_section: null,
            text: {
                id: null,
                type: "HTML",
                content:
                    "Degree of the zero polynomial is <br> (a.) 0 <br> (b.) 1 <br> (c.) any natural number <br> (d.) not defined",
            },
            media_id: null,
            created_at: null,
            updated_at: null,
            question_response_type: "OPTION",
            question_type: "MCQS",
            access_level: "PUBLIC",
            auto_evaluation_json: '{"type":"MCQS","data":null}',
            options_json: null,
            parsed_evaluation_object: null,
            evaluation_type: null,
            explanation_text: {
                id: null,
                type: "HTML",
                content: "Degree of zero polynomial is not defined.",
            },
            default_question_time_mins: null,
            parent_rich_text_id: null,
            parent_rich_text: null,
            options: [
                {
                    id: null,
                    preview_id: "0",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "0",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "1",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "1",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "2",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "any natural number",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "3",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "not defined",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
            ],
            errors: [],
            warnings: [],
            tags: ["polynomial", "zero polynomial"],
            level: "easy",
        },
        {
            id: null,
            preview_id: null,
            section_id: null,
            question_order_in_section: null,
            text: {
                id: null,
                type: "HTML",
                content: "If ",
            },
            media_id: null,
            created_at: null,
            updated_at: null,
            question_response_type: "OPTION",
            question_type: "MCQS",
            access_level: "PUBLIC",
            auto_evaluation_json: '{"type":"MCQS","data":null}',
            options_json: null,
            parsed_evaluation_object: null,
            evaluation_type: null,
            explanation_text: {
                id: null,
                type: "HTML",
                content: "",
            },
            default_question_time_mins: null,
            parent_rich_text_id: null,
            parent_rich_text: null,
            options: [
                {
                    id: null,
                    preview_id: "0",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "0",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "1",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "1",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "2",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
                {
                    id: null,
                    preview_id: "3",
                    question_id: null,
                    text: {
                        id: null,
                        type: "HTML",
                        content: "",
                    },
                    media_id: null,
                    option_order: null,
                    created_on: null,
                    updated_on: null,
                    explanation_text: null,
                },
            ],
            errors: [],
            warnings: [],
            tags: ["polynomial", "equation"],
            level: "medium",
        },
    ],
    title: "Polynomial Questions",
    tags: ["polynomial", "degree", "zero polynomial", "equation"],
    difficulty: "easy",
    description: null,
    subjects: ["Mathematics"],
    classes: ["class 9", "class 10", "class 11", "class 12"],
};
