/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as StudyLibraryIndexImport } from './routes/study-library/index';
import { Route as SignupIndexImport } from './routes/signup/index';
import { Route as ManageStudentsIndexImport } from './routes/manage-students/index';
import { Route as ManageInstituteIndexImport } from './routes/manage-institute/index';
import { Route as LoginIndexImport } from './routes/login/index';
import { Route as EvaluatorAiIndexImport } from './routes/evaluator-ai/index';
import { Route as EvaluationIndexImport } from './routes/evaluation/index';
import { Route as DashboardIndexImport } from './routes/dashboard/index';
import { Route as CommunityIndexImport } from './routes/community/index';
import { Route as AssessmentIndexImport } from './routes/assessment/index';
import { Route as AiCenterIndexImport } from './routes/ai-center/index';
import { Route as StudyLibraryReportsIndexImport } from './routes/study-library/reports/index';
import { Route as StudyLibraryPresentIndexImport } from './routes/study-library/present/index';
import { Route as StudyLibraryCoursesIndexImport } from './routes/study-library/courses/index';
import { Route as SignupOnboardingIndexImport } from './routes/signup/onboarding/index';
import { Route as ManageStudentsStudentsListIndexImport } from './routes/manage-students/students-list/index';
import { Route as ManageStudentsInviteIndexImport } from './routes/manage-students/invite/index';
import { Route as ManageStudentsEnrollRequestsIndexImport } from './routes/manage-students/enroll-requests/index';
import { Route as ManageInstituteTeamsIndexImport } from './routes/manage-institute/teams/index';
import { Route as ManageInstituteSessionsIndexImport } from './routes/manage-institute/sessions/index';
import { Route as ManageInstituteBatchesIndexImport } from './routes/manage-institute/batches/index';
import { Route as LoginForgotPasswordIndexImport } from './routes/login/forgot-password/index';
import { Route as LoginKeyIndexImport } from './routes/login/$key/index';
import { Route as HomeworkCreationAssessmentListIndexImport } from './routes/homework-creation/assessment-list/index';
import { Route as EvaluatorAiStudentsIndexImport } from './routes/evaluator-ai/students/index';
import { Route as EvaluatorAiEvaluationIndexImport } from './routes/evaluator-ai/evaluation/index';
import { Route as EvaluatorAiAssessmentIndexImport } from './routes/evaluator-ai/assessment/index';
import { Route as EvaluationEvaluationsIndexImport } from './routes/evaluation/evaluations/index';
import { Route as EvaluationEvaluationToolIndexImport } from './routes/evaluation/evaluation-tool/index';
import { Route as CommunityQuestionPaperIndexImport } from './routes/community/question-paper/index';
import { Route as AssessmentQuestionPapersIndexImport } from './routes/assessment/question-papers/index';
import { Route as AssessmentAssessmentListIndexImport } from './routes/assessment/assessment-list/index';
import { Route as AiCenterAiToolsIndexImport } from './routes/ai-center/ai-tools/index';
import { Route as StudyLibraryPresentAddIndexImport } from './routes/study-library/present/add/index';
import { Route as StudyLibraryCoursesLevelsIndexImport } from './routes/study-library/courses/levels/index';
import { Route as EvaluatorAiEvaluationStudentSummaryIndexImport } from './routes/evaluator-ai/evaluation/student-summary/index';
import { Route as EvaluatorAiAssessmentCreateAssessmentIndexImport } from './routes/evaluator-ai/assessment/create-assessment/index';
import { Route as AssessmentExportAssessmentIdIndexImport } from './routes/assessment/export/$assessmentId/index';
import { Route as AiCenterAiToolsVsmartUploadIndexImport } from './routes/ai-center/ai-tools/vsmart-upload/index';
import { Route as AiCenterAiToolsVsmartSorterIndexImport } from './routes/ai-center/ai-tools/vsmart-sorter/index';
import { Route as AiCenterAiToolsVsmartPromptIndexImport } from './routes/ai-center/ai-tools/vsmart-prompt/index';
import { Route as AiCenterAiToolsVsmartOrganizerIndexImport } from './routes/ai-center/ai-tools/vsmart-organizer/index';
import { Route as AiCenterAiToolsVsmartLectureIndexImport } from './routes/ai-center/ai-tools/vsmart-lecture/index';
import { Route as AiCenterAiToolsVsmartImageIndexImport } from './routes/ai-center/ai-tools/vsmart-image/index';
import { Route as AiCenterAiToolsVsmartFeedbackIndexImport } from './routes/ai-center/ai-tools/vsmart-feedback/index';
import { Route as AiCenterAiToolsVsmartExtractIndexImport } from './routes/ai-center/ai-tools/vsmart-extract/index';
import { Route as AiCenterAiToolsVsmartChatIndexImport } from './routes/ai-center/ai-tools/vsmart-chat/index';
import { Route as AiCenterAiToolsVsmartAudioIndexImport } from './routes/ai-center/ai-tools/vsmart-audio/index';
import { Route as StudyLibraryCoursesLevelsSubjectsIndexImport } from './routes/study-library/courses/levels/subjects/index';
import { Route as HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexImport } from './routes/homework-creation/create-assessment/$assessmentId/$examtype/index';
import { Route as AssessmentCreateAssessmentAssessmentIdExamtypeIndexImport } from './routes/assessment/create-assessment/$assessmentId/$examtype/index';
import { Route as StudyLibraryCoursesLevelsSubjectsModulesIndexImport } from './routes/study-library/courses/levels/subjects/modules/index';
import { Route as EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexImport } from './routes/evaluation/evaluate/$assessmentId/$attemptId/$examType/index';
import { Route as StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexImport } from './routes/study-library/courses/levels/subjects/modules/chapters/index';
import { Route as EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexImport } from './routes/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/index';
import { Route as StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexImport } from './routes/study-library/courses/levels/subjects/modules/chapters/slides/index';
import { Route as HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexImport } from './routes/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/index';
import { Route as AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexImport } from './routes/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/index';

// Create/Update Routes

const StudyLibraryIndexRoute = StudyLibraryIndexImport.update({
    id: '/study-library/',
    path: '/study-library/',
    getParentRoute: () => rootRoute,
} as any);

const SignupIndexRoute = SignupIndexImport.update({
    id: '/signup/',
    path: '/signup/',
    getParentRoute: () => rootRoute,
} as any);

const ManageStudentsIndexRoute = ManageStudentsIndexImport.update({
    id: '/manage-students/',
    path: '/manage-students/',
    getParentRoute: () => rootRoute,
} as any);

const ManageInstituteIndexRoute = ManageInstituteIndexImport.update({
    id: '/manage-institute/',
    path: '/manage-institute/',
    getParentRoute: () => rootRoute,
} as any);

const LoginIndexRoute = LoginIndexImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluatorAiIndexRoute = EvaluatorAiIndexImport.update({
    id: '/evaluator-ai/',
    path: '/evaluator-ai/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluationIndexRoute = EvaluationIndexImport.update({
    id: '/evaluation/',
    path: '/evaluation/',
    getParentRoute: () => rootRoute,
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => rootRoute,
} as any);

const CommunityIndexRoute = CommunityIndexImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => rootRoute,
} as any);

const AssessmentIndexRoute = AssessmentIndexImport.update({
    id: '/assessment/',
    path: '/assessment/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterIndexRoute = AiCenterIndexImport.update({
    id: '/ai-center/',
    path: '/ai-center/',
    getParentRoute: () => rootRoute,
} as any);

const StudyLibraryReportsIndexRoute = StudyLibraryReportsIndexImport.update({
    id: '/study-library/reports/',
    path: '/study-library/reports/',
    getParentRoute: () => rootRoute,
} as any);

const StudyLibraryPresentIndexRoute = StudyLibraryPresentIndexImport.update({
    id: '/study-library/present/',
    path: '/study-library/present/',
    getParentRoute: () => rootRoute,
} as any);

const StudyLibraryCoursesIndexRoute = StudyLibraryCoursesIndexImport.update({
    id: '/study-library/courses/',
    path: '/study-library/courses/',
    getParentRoute: () => rootRoute,
} as any);

const SignupOnboardingIndexRoute = SignupOnboardingIndexImport.update({
    id: '/signup/onboarding/',
    path: '/signup/onboarding/',
    getParentRoute: () => rootRoute,
} as any);

const ManageStudentsStudentsListIndexRoute = ManageStudentsStudentsListIndexImport.update({
    id: '/manage-students/students-list/',
    path: '/manage-students/students-list/',
    getParentRoute: () => rootRoute,
} as any);

const ManageStudentsInviteIndexRoute = ManageStudentsInviteIndexImport.update({
    id: '/manage-students/invite/',
    path: '/manage-students/invite/',
    getParentRoute: () => rootRoute,
} as any);

const ManageStudentsEnrollRequestsIndexRoute = ManageStudentsEnrollRequestsIndexImport.update({
    id: '/manage-students/enroll-requests/',
    path: '/manage-students/enroll-requests/',
    getParentRoute: () => rootRoute,
} as any);

const ManageInstituteTeamsIndexRoute = ManageInstituteTeamsIndexImport.update({
    id: '/manage-institute/teams/',
    path: '/manage-institute/teams/',
    getParentRoute: () => rootRoute,
} as any);

const ManageInstituteSessionsIndexRoute = ManageInstituteSessionsIndexImport.update({
    id: '/manage-institute/sessions/',
    path: '/manage-institute/sessions/',
    getParentRoute: () => rootRoute,
} as any);

const ManageInstituteBatchesIndexRoute = ManageInstituteBatchesIndexImport.update({
    id: '/manage-institute/batches/',
    path: '/manage-institute/batches/',
    getParentRoute: () => rootRoute,
} as any);

const LoginForgotPasswordIndexRoute = LoginForgotPasswordIndexImport.update({
    id: '/login/forgot-password/',
    path: '/login/forgot-password/',
    getParentRoute: () => rootRoute,
} as any);

const LoginKeyIndexRoute = LoginKeyIndexImport.update({
    id: '/login/$key/',
    path: '/login/$key/',
    getParentRoute: () => rootRoute,
} as any);

const HomeworkCreationAssessmentListIndexRoute = HomeworkCreationAssessmentListIndexImport.update({
    id: '/homework-creation/assessment-list/',
    path: '/homework-creation/assessment-list/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluatorAiStudentsIndexRoute = EvaluatorAiStudentsIndexImport.update({
    id: '/evaluator-ai/students/',
    path: '/evaluator-ai/students/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluatorAiEvaluationIndexRoute = EvaluatorAiEvaluationIndexImport.update({
    id: '/evaluator-ai/evaluation/',
    path: '/evaluator-ai/evaluation/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluatorAiAssessmentIndexRoute = EvaluatorAiAssessmentIndexImport.update({
    id: '/evaluator-ai/assessment/',
    path: '/evaluator-ai/assessment/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluationEvaluationsIndexRoute = EvaluationEvaluationsIndexImport.update({
    id: '/evaluation/evaluations/',
    path: '/evaluation/evaluations/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluationEvaluationToolIndexRoute = EvaluationEvaluationToolIndexImport.update({
    id: '/evaluation/evaluation-tool/',
    path: '/evaluation/evaluation-tool/',
    getParentRoute: () => rootRoute,
} as any);

const CommunityQuestionPaperIndexRoute = CommunityQuestionPaperIndexImport.update({
    id: '/community/question-paper/',
    path: '/community/question-paper/',
    getParentRoute: () => rootRoute,
} as any);

const AssessmentQuestionPapersIndexRoute = AssessmentQuestionPapersIndexImport.update({
    id: '/assessment/question-papers/',
    path: '/assessment/question-papers/',
    getParentRoute: () => rootRoute,
} as any);

const AssessmentAssessmentListIndexRoute = AssessmentAssessmentListIndexImport.update({
    id: '/assessment/assessment-list/',
    path: '/assessment/assessment-list/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsIndexRoute = AiCenterAiToolsIndexImport.update({
    id: '/ai-center/ai-tools/',
    path: '/ai-center/ai-tools/',
    getParentRoute: () => rootRoute,
} as any);

const StudyLibraryPresentAddIndexRoute = StudyLibraryPresentAddIndexImport.update({
    id: '/study-library/present/add/',
    path: '/study-library/present/add/',
    getParentRoute: () => rootRoute,
} as any);

const StudyLibraryCoursesLevelsIndexRoute = StudyLibraryCoursesLevelsIndexImport.update({
    id: '/study-library/courses/levels/',
    path: '/study-library/courses/levels/',
    getParentRoute: () => rootRoute,
} as any);

const EvaluatorAiEvaluationStudentSummaryIndexRoute =
    EvaluatorAiEvaluationStudentSummaryIndexImport.update({
        id: '/evaluator-ai/evaluation/student-summary/',
        path: '/evaluator-ai/evaluation/student-summary/',
        getParentRoute: () => rootRoute,
    } as any);

const EvaluatorAiAssessmentCreateAssessmentIndexRoute =
    EvaluatorAiAssessmentCreateAssessmentIndexImport.update({
        id: '/evaluator-ai/assessment/create-assessment/',
        path: '/evaluator-ai/assessment/create-assessment/',
        getParentRoute: () => rootRoute,
    } as any);

const AssessmentExportAssessmentIdIndexRoute = AssessmentExportAssessmentIdIndexImport.update({
    id: '/assessment/export/$assessmentId/',
    path: '/assessment/export/$assessmentId/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartUploadIndexRoute = AiCenterAiToolsVsmartUploadIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-upload/',
    path: '/ai-center/ai-tools/vsmart-upload/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartSorterIndexRoute = AiCenterAiToolsVsmartSorterIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-sorter/',
    path: '/ai-center/ai-tools/vsmart-sorter/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartPromptIndexRoute = AiCenterAiToolsVsmartPromptIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-prompt/',
    path: '/ai-center/ai-tools/vsmart-prompt/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartOrganizerIndexRoute = AiCenterAiToolsVsmartOrganizerIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-organizer/',
    path: '/ai-center/ai-tools/vsmart-organizer/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartLectureIndexRoute = AiCenterAiToolsVsmartLectureIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-lecture/',
    path: '/ai-center/ai-tools/vsmart-lecture/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartImageIndexRoute = AiCenterAiToolsVsmartImageIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-image/',
    path: '/ai-center/ai-tools/vsmart-image/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartFeedbackIndexRoute = AiCenterAiToolsVsmartFeedbackIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-feedback/',
    path: '/ai-center/ai-tools/vsmart-feedback/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartExtractIndexRoute = AiCenterAiToolsVsmartExtractIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-extract/',
    path: '/ai-center/ai-tools/vsmart-extract/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartChatIndexRoute = AiCenterAiToolsVsmartChatIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-chat/',
    path: '/ai-center/ai-tools/vsmart-chat/',
    getParentRoute: () => rootRoute,
} as any);

const AiCenterAiToolsVsmartAudioIndexRoute = AiCenterAiToolsVsmartAudioIndexImport.update({
    id: '/ai-center/ai-tools/vsmart-audio/',
    path: '/ai-center/ai-tools/vsmart-audio/',
    getParentRoute: () => rootRoute,
} as any);

const StudyLibraryCoursesLevelsSubjectsIndexRoute =
    StudyLibraryCoursesLevelsSubjectsIndexImport.update({
        id: '/study-library/courses/levels/subjects/',
        path: '/study-library/courses/levels/subjects/',
        getParentRoute: () => rootRoute,
    } as any);

const HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute =
    HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexImport.update({
        id: '/homework-creation/create-assessment/$assessmentId/$examtype/',
        path: '/homework-creation/create-assessment/$assessmentId/$examtype/',
        getParentRoute: () => rootRoute,
    } as any);

const AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute =
    AssessmentCreateAssessmentAssessmentIdExamtypeIndexImport.update({
        id: '/assessment/create-assessment/$assessmentId/$examtype/',
        path: '/assessment/create-assessment/$assessmentId/$examtype/',
        getParentRoute: () => rootRoute,
    } as any);

const StudyLibraryCoursesLevelsSubjectsModulesIndexRoute =
    StudyLibraryCoursesLevelsSubjectsModulesIndexImport.update({
        id: '/study-library/courses/levels/subjects/modules/',
        path: '/study-library/courses/levels/subjects/modules/',
        getParentRoute: () => rootRoute,
    } as any);

const EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute =
    EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexImport.update({
        id: '/evaluation/evaluate/$assessmentId/$attemptId/$examType/',
        path: '/evaluation/evaluate/$assessmentId/$attemptId/$examType/',
        getParentRoute: () => rootRoute,
    } as any);

const StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute =
    StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexImport.update({
        id: '/study-library/courses/levels/subjects/modules/chapters/',
        path: '/study-library/courses/levels/subjects/modules/chapters/',
        getParentRoute: () => rootRoute,
    } as any);

const EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute =
    EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexImport.update({
        id: '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/',
        path: '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/',
        getParentRoute: () => rootRoute,
    } as any);

const StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute =
    StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexImport.update({
        id: '/study-library/courses/levels/subjects/modules/chapters/slides/',
        path: '/study-library/courses/levels/subjects/modules/chapters/slides/',
        getParentRoute: () => rootRoute,
    } as any);

const HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute =
    HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexImport.update(
        {
            id: '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/',
            path: '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/',
            getParentRoute: () => rootRoute,
        } as any
    );

const AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute =
    AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexImport.update(
        {
            id: '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/',
            path: '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/',
            getParentRoute: () => rootRoute,
        } as any
    );

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/ai-center/': {
            id: '/ai-center/';
            path: '/ai-center';
            fullPath: '/ai-center';
            preLoaderRoute: typeof AiCenterIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/assessment/': {
            id: '/assessment/';
            path: '/assessment';
            fullPath: '/assessment';
            preLoaderRoute: typeof AssessmentIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/community/': {
            id: '/community/';
            path: '/community';
            fullPath: '/community';
            preLoaderRoute: typeof CommunityIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/dashboard/': {
            id: '/dashboard/';
            path: '/dashboard';
            fullPath: '/dashboard';
            preLoaderRoute: typeof DashboardIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluation/': {
            id: '/evaluation/';
            path: '/evaluation';
            fullPath: '/evaluation';
            preLoaderRoute: typeof EvaluationIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluator-ai/': {
            id: '/evaluator-ai/';
            path: '/evaluator-ai';
            fullPath: '/evaluator-ai';
            preLoaderRoute: typeof EvaluatorAiIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/login/': {
            id: '/login/';
            path: '/login';
            fullPath: '/login';
            preLoaderRoute: typeof LoginIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-institute/': {
            id: '/manage-institute/';
            path: '/manage-institute';
            fullPath: '/manage-institute';
            preLoaderRoute: typeof ManageInstituteIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-students/': {
            id: '/manage-students/';
            path: '/manage-students';
            fullPath: '/manage-students';
            preLoaderRoute: typeof ManageStudentsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/signup/': {
            id: '/signup/';
            path: '/signup';
            fullPath: '/signup';
            preLoaderRoute: typeof SignupIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/': {
            id: '/study-library/';
            path: '/study-library';
            fullPath: '/study-library';
            preLoaderRoute: typeof StudyLibraryIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/': {
            id: '/ai-center/ai-tools/';
            path: '/ai-center/ai-tools';
            fullPath: '/ai-center/ai-tools';
            preLoaderRoute: typeof AiCenterAiToolsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/assessment/assessment-list/': {
            id: '/assessment/assessment-list/';
            path: '/assessment/assessment-list';
            fullPath: '/assessment/assessment-list';
            preLoaderRoute: typeof AssessmentAssessmentListIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/assessment/question-papers/': {
            id: '/assessment/question-papers/';
            path: '/assessment/question-papers';
            fullPath: '/assessment/question-papers';
            preLoaderRoute: typeof AssessmentQuestionPapersIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/community/question-paper/': {
            id: '/community/question-paper/';
            path: '/community/question-paper';
            fullPath: '/community/question-paper';
            preLoaderRoute: typeof CommunityQuestionPaperIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluation/evaluation-tool/': {
            id: '/evaluation/evaluation-tool/';
            path: '/evaluation/evaluation-tool';
            fullPath: '/evaluation/evaluation-tool';
            preLoaderRoute: typeof EvaluationEvaluationToolIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluation/evaluations/': {
            id: '/evaluation/evaluations/';
            path: '/evaluation/evaluations';
            fullPath: '/evaluation/evaluations';
            preLoaderRoute: typeof EvaluationEvaluationsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluator-ai/assessment/': {
            id: '/evaluator-ai/assessment/';
            path: '/evaluator-ai/assessment';
            fullPath: '/evaluator-ai/assessment';
            preLoaderRoute: typeof EvaluatorAiAssessmentIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluator-ai/evaluation/': {
            id: '/evaluator-ai/evaluation/';
            path: '/evaluator-ai/evaluation';
            fullPath: '/evaluator-ai/evaluation';
            preLoaderRoute: typeof EvaluatorAiEvaluationIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluator-ai/students/': {
            id: '/evaluator-ai/students/';
            path: '/evaluator-ai/students';
            fullPath: '/evaluator-ai/students';
            preLoaderRoute: typeof EvaluatorAiStudentsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/homework-creation/assessment-list/': {
            id: '/homework-creation/assessment-list/';
            path: '/homework-creation/assessment-list';
            fullPath: '/homework-creation/assessment-list';
            preLoaderRoute: typeof HomeworkCreationAssessmentListIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/login/$key/': {
            id: '/login/$key/';
            path: '/login/$key';
            fullPath: '/login/$key';
            preLoaderRoute: typeof LoginKeyIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/login/forgot-password/': {
            id: '/login/forgot-password/';
            path: '/login/forgot-password';
            fullPath: '/login/forgot-password';
            preLoaderRoute: typeof LoginForgotPasswordIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-institute/batches/': {
            id: '/manage-institute/batches/';
            path: '/manage-institute/batches';
            fullPath: '/manage-institute/batches';
            preLoaderRoute: typeof ManageInstituteBatchesIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-institute/sessions/': {
            id: '/manage-institute/sessions/';
            path: '/manage-institute/sessions';
            fullPath: '/manage-institute/sessions';
            preLoaderRoute: typeof ManageInstituteSessionsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-institute/teams/': {
            id: '/manage-institute/teams/';
            path: '/manage-institute/teams';
            fullPath: '/manage-institute/teams';
            preLoaderRoute: typeof ManageInstituteTeamsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-students/enroll-requests/': {
            id: '/manage-students/enroll-requests/';
            path: '/manage-students/enroll-requests';
            fullPath: '/manage-students/enroll-requests';
            preLoaderRoute: typeof ManageStudentsEnrollRequestsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-students/invite/': {
            id: '/manage-students/invite/';
            path: '/manage-students/invite';
            fullPath: '/manage-students/invite';
            preLoaderRoute: typeof ManageStudentsInviteIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/manage-students/students-list/': {
            id: '/manage-students/students-list/';
            path: '/manage-students/students-list';
            fullPath: '/manage-students/students-list';
            preLoaderRoute: typeof ManageStudentsStudentsListIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/signup/onboarding/': {
            id: '/signup/onboarding/';
            path: '/signup/onboarding';
            fullPath: '/signup/onboarding';
            preLoaderRoute: typeof SignupOnboardingIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/courses/': {
            id: '/study-library/courses/';
            path: '/study-library/courses';
            fullPath: '/study-library/courses';
            preLoaderRoute: typeof StudyLibraryCoursesIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/present/': {
            id: '/study-library/present/';
            path: '/study-library/present';
            fullPath: '/study-library/present';
            preLoaderRoute: typeof StudyLibraryPresentIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/reports/': {
            id: '/study-library/reports/';
            path: '/study-library/reports';
            fullPath: '/study-library/reports';
            preLoaderRoute: typeof StudyLibraryReportsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-audio/': {
            id: '/ai-center/ai-tools/vsmart-audio/';
            path: '/ai-center/ai-tools/vsmart-audio';
            fullPath: '/ai-center/ai-tools/vsmart-audio';
            preLoaderRoute: typeof AiCenterAiToolsVsmartAudioIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-chat/': {
            id: '/ai-center/ai-tools/vsmart-chat/';
            path: '/ai-center/ai-tools/vsmart-chat';
            fullPath: '/ai-center/ai-tools/vsmart-chat';
            preLoaderRoute: typeof AiCenterAiToolsVsmartChatIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-extract/': {
            id: '/ai-center/ai-tools/vsmart-extract/';
            path: '/ai-center/ai-tools/vsmart-extract';
            fullPath: '/ai-center/ai-tools/vsmart-extract';
            preLoaderRoute: typeof AiCenterAiToolsVsmartExtractIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-feedback/': {
            id: '/ai-center/ai-tools/vsmart-feedback/';
            path: '/ai-center/ai-tools/vsmart-feedback';
            fullPath: '/ai-center/ai-tools/vsmart-feedback';
            preLoaderRoute: typeof AiCenterAiToolsVsmartFeedbackIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-image/': {
            id: '/ai-center/ai-tools/vsmart-image/';
            path: '/ai-center/ai-tools/vsmart-image';
            fullPath: '/ai-center/ai-tools/vsmart-image';
            preLoaderRoute: typeof AiCenterAiToolsVsmartImageIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-lecture/': {
            id: '/ai-center/ai-tools/vsmart-lecture/';
            path: '/ai-center/ai-tools/vsmart-lecture';
            fullPath: '/ai-center/ai-tools/vsmart-lecture';
            preLoaderRoute: typeof AiCenterAiToolsVsmartLectureIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-organizer/': {
            id: '/ai-center/ai-tools/vsmart-organizer/';
            path: '/ai-center/ai-tools/vsmart-organizer';
            fullPath: '/ai-center/ai-tools/vsmart-organizer';
            preLoaderRoute: typeof AiCenterAiToolsVsmartOrganizerIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-prompt/': {
            id: '/ai-center/ai-tools/vsmart-prompt/';
            path: '/ai-center/ai-tools/vsmart-prompt';
            fullPath: '/ai-center/ai-tools/vsmart-prompt';
            preLoaderRoute: typeof AiCenterAiToolsVsmartPromptIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-sorter/': {
            id: '/ai-center/ai-tools/vsmart-sorter/';
            path: '/ai-center/ai-tools/vsmart-sorter';
            fullPath: '/ai-center/ai-tools/vsmart-sorter';
            preLoaderRoute: typeof AiCenterAiToolsVsmartSorterIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/ai-center/ai-tools/vsmart-upload/': {
            id: '/ai-center/ai-tools/vsmart-upload/';
            path: '/ai-center/ai-tools/vsmart-upload';
            fullPath: '/ai-center/ai-tools/vsmart-upload';
            preLoaderRoute: typeof AiCenterAiToolsVsmartUploadIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/assessment/export/$assessmentId/': {
            id: '/assessment/export/$assessmentId/';
            path: '/assessment/export/$assessmentId';
            fullPath: '/assessment/export/$assessmentId';
            preLoaderRoute: typeof AssessmentExportAssessmentIdIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluator-ai/assessment/create-assessment/': {
            id: '/evaluator-ai/assessment/create-assessment/';
            path: '/evaluator-ai/assessment/create-assessment';
            fullPath: '/evaluator-ai/assessment/create-assessment';
            preLoaderRoute: typeof EvaluatorAiAssessmentCreateAssessmentIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluator-ai/evaluation/student-summary/': {
            id: '/evaluator-ai/evaluation/student-summary/';
            path: '/evaluator-ai/evaluation/student-summary';
            fullPath: '/evaluator-ai/evaluation/student-summary';
            preLoaderRoute: typeof EvaluatorAiEvaluationStudentSummaryIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/courses/levels/': {
            id: '/study-library/courses/levels/';
            path: '/study-library/courses/levels';
            fullPath: '/study-library/courses/levels';
            preLoaderRoute: typeof StudyLibraryCoursesLevelsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/present/add/': {
            id: '/study-library/present/add/';
            path: '/study-library/present/add';
            fullPath: '/study-library/present/add';
            preLoaderRoute: typeof StudyLibraryPresentAddIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/assessment/create-assessment/$assessmentId/$examtype/': {
            id: '/assessment/create-assessment/$assessmentId/$examtype/';
            path: '/assessment/create-assessment/$assessmentId/$examtype';
            fullPath: '/assessment/create-assessment/$assessmentId/$examtype';
            preLoaderRoute: typeof AssessmentCreateAssessmentAssessmentIdExamtypeIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/homework-creation/create-assessment/$assessmentId/$examtype/': {
            id: '/homework-creation/create-assessment/$assessmentId/$examtype/';
            path: '/homework-creation/create-assessment/$assessmentId/$examtype';
            fullPath: '/homework-creation/create-assessment/$assessmentId/$examtype';
            preLoaderRoute: typeof HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/courses/levels/subjects/': {
            id: '/study-library/courses/levels/subjects/';
            path: '/study-library/courses/levels/subjects';
            fullPath: '/study-library/courses/levels/subjects';
            preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluation/evaluate/$assessmentId/$attemptId/$examType/': {
            id: '/evaluation/evaluate/$assessmentId/$attemptId/$examType/';
            path: '/evaluation/evaluate/$assessmentId/$attemptId/$examType';
            fullPath: '/evaluation/evaluate/$assessmentId/$attemptId/$examType';
            preLoaderRoute: typeof EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/courses/levels/subjects/modules/': {
            id: '/study-library/courses/levels/subjects/modules/';
            path: '/study-library/courses/levels/subjects/modules';
            fullPath: '/study-library/courses/levels/subjects/modules';
            preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/': {
            id: '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/';
            path: '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType';
            fullPath: '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType';
            preLoaderRoute: typeof EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/courses/levels/subjects/modules/chapters/': {
            id: '/study-library/courses/levels/subjects/modules/chapters/';
            path: '/study-library/courses/levels/subjects/modules/chapters';
            fullPath: '/study-library/courses/levels/subjects/modules/chapters';
            preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/': {
            id: '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/';
            path: '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab';
            fullPath: '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab';
            preLoaderRoute: typeof AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/': {
            id: '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/';
            path: '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab';
            fullPath: '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab';
            preLoaderRoute: typeof HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexImport;
            parentRoute: typeof rootRoute;
        };
        '/study-library/courses/levels/subjects/modules/chapters/slides/': {
            id: '/study-library/courses/levels/subjects/modules/chapters/slides/';
            path: '/study-library/courses/levels/subjects/modules/chapters/slides';
            fullPath: '/study-library/courses/levels/subjects/modules/chapters/slides';
            preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/ai-center': typeof AiCenterIndexRoute;
    '/assessment': typeof AssessmentIndexRoute;
    '/community': typeof CommunityIndexRoute;
    '/dashboard': typeof DashboardIndexRoute;
    '/evaluation': typeof EvaluationIndexRoute;
    '/evaluator-ai': typeof EvaluatorAiIndexRoute;
    '/login': typeof LoginIndexRoute;
    '/manage-institute': typeof ManageInstituteIndexRoute;
    '/manage-students': typeof ManageStudentsIndexRoute;
    '/signup': typeof SignupIndexRoute;
    '/study-library': typeof StudyLibraryIndexRoute;
    '/ai-center/ai-tools': typeof AiCenterAiToolsIndexRoute;
    '/assessment/assessment-list': typeof AssessmentAssessmentListIndexRoute;
    '/assessment/question-papers': typeof AssessmentQuestionPapersIndexRoute;
    '/community/question-paper': typeof CommunityQuestionPaperIndexRoute;
    '/evaluation/evaluation-tool': typeof EvaluationEvaluationToolIndexRoute;
    '/evaluation/evaluations': typeof EvaluationEvaluationsIndexRoute;
    '/evaluator-ai/assessment': typeof EvaluatorAiAssessmentIndexRoute;
    '/evaluator-ai/evaluation': typeof EvaluatorAiEvaluationIndexRoute;
    '/evaluator-ai/students': typeof EvaluatorAiStudentsIndexRoute;
    '/homework-creation/assessment-list': typeof HomeworkCreationAssessmentListIndexRoute;
    '/login/$key': typeof LoginKeyIndexRoute;
    '/login/forgot-password': typeof LoginForgotPasswordIndexRoute;
    '/manage-institute/batches': typeof ManageInstituteBatchesIndexRoute;
    '/manage-institute/sessions': typeof ManageInstituteSessionsIndexRoute;
    '/manage-institute/teams': typeof ManageInstituteTeamsIndexRoute;
    '/manage-students/enroll-requests': typeof ManageStudentsEnrollRequestsIndexRoute;
    '/manage-students/invite': typeof ManageStudentsInviteIndexRoute;
    '/manage-students/students-list': typeof ManageStudentsStudentsListIndexRoute;
    '/signup/onboarding': typeof SignupOnboardingIndexRoute;
    '/study-library/courses': typeof StudyLibraryCoursesIndexRoute;
    '/study-library/present': typeof StudyLibraryPresentIndexRoute;
    '/study-library/reports': typeof StudyLibraryReportsIndexRoute;
    '/ai-center/ai-tools/vsmart-audio': typeof AiCenterAiToolsVsmartAudioIndexRoute;
    '/ai-center/ai-tools/vsmart-chat': typeof AiCenterAiToolsVsmartChatIndexRoute;
    '/ai-center/ai-tools/vsmart-extract': typeof AiCenterAiToolsVsmartExtractIndexRoute;
    '/ai-center/ai-tools/vsmart-feedback': typeof AiCenterAiToolsVsmartFeedbackIndexRoute;
    '/ai-center/ai-tools/vsmart-image': typeof AiCenterAiToolsVsmartImageIndexRoute;
    '/ai-center/ai-tools/vsmart-lecture': typeof AiCenterAiToolsVsmartLectureIndexRoute;
    '/ai-center/ai-tools/vsmart-organizer': typeof AiCenterAiToolsVsmartOrganizerIndexRoute;
    '/ai-center/ai-tools/vsmart-prompt': typeof AiCenterAiToolsVsmartPromptIndexRoute;
    '/ai-center/ai-tools/vsmart-sorter': typeof AiCenterAiToolsVsmartSorterIndexRoute;
    '/ai-center/ai-tools/vsmart-upload': typeof AiCenterAiToolsVsmartUploadIndexRoute;
    '/assessment/export/$assessmentId': typeof AssessmentExportAssessmentIdIndexRoute;
    '/evaluator-ai/assessment/create-assessment': typeof EvaluatorAiAssessmentCreateAssessmentIndexRoute;
    '/evaluator-ai/evaluation/student-summary': typeof EvaluatorAiEvaluationStudentSummaryIndexRoute;
    '/study-library/courses/levels': typeof StudyLibraryCoursesLevelsIndexRoute;
    '/study-library/present/add': typeof StudyLibraryPresentAddIndexRoute;
    '/assessment/create-assessment/$assessmentId/$examtype': typeof AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute;
    '/homework-creation/create-assessment/$assessmentId/$examtype': typeof HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute;
    '/study-library/courses/levels/subjects': typeof StudyLibraryCoursesLevelsSubjectsIndexRoute;
    '/evaluation/evaluate/$assessmentId/$attemptId/$examType': typeof EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute;
    '/study-library/courses/levels/subjects/modules': typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute;
    '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType': typeof EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute;
    '/study-library/courses/levels/subjects/modules/chapters': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute;
    '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab': typeof AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab': typeof HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    '/study-library/courses/levels/subjects/modules/chapters/slides': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute;
}

export interface FileRoutesByTo {
    '/ai-center': typeof AiCenterIndexRoute;
    '/assessment': typeof AssessmentIndexRoute;
    '/community': typeof CommunityIndexRoute;
    '/dashboard': typeof DashboardIndexRoute;
    '/evaluation': typeof EvaluationIndexRoute;
    '/evaluator-ai': typeof EvaluatorAiIndexRoute;
    '/login': typeof LoginIndexRoute;
    '/manage-institute': typeof ManageInstituteIndexRoute;
    '/manage-students': typeof ManageStudentsIndexRoute;
    '/signup': typeof SignupIndexRoute;
    '/study-library': typeof StudyLibraryIndexRoute;
    '/ai-center/ai-tools': typeof AiCenterAiToolsIndexRoute;
    '/assessment/assessment-list': typeof AssessmentAssessmentListIndexRoute;
    '/assessment/question-papers': typeof AssessmentQuestionPapersIndexRoute;
    '/community/question-paper': typeof CommunityQuestionPaperIndexRoute;
    '/evaluation/evaluation-tool': typeof EvaluationEvaluationToolIndexRoute;
    '/evaluation/evaluations': typeof EvaluationEvaluationsIndexRoute;
    '/evaluator-ai/assessment': typeof EvaluatorAiAssessmentIndexRoute;
    '/evaluator-ai/evaluation': typeof EvaluatorAiEvaluationIndexRoute;
    '/evaluator-ai/students': typeof EvaluatorAiStudentsIndexRoute;
    '/homework-creation/assessment-list': typeof HomeworkCreationAssessmentListIndexRoute;
    '/login/$key': typeof LoginKeyIndexRoute;
    '/login/forgot-password': typeof LoginForgotPasswordIndexRoute;
    '/manage-institute/batches': typeof ManageInstituteBatchesIndexRoute;
    '/manage-institute/sessions': typeof ManageInstituteSessionsIndexRoute;
    '/manage-institute/teams': typeof ManageInstituteTeamsIndexRoute;
    '/manage-students/enroll-requests': typeof ManageStudentsEnrollRequestsIndexRoute;
    '/manage-students/invite': typeof ManageStudentsInviteIndexRoute;
    '/manage-students/students-list': typeof ManageStudentsStudentsListIndexRoute;
    '/signup/onboarding': typeof SignupOnboardingIndexRoute;
    '/study-library/courses': typeof StudyLibraryCoursesIndexRoute;
    '/study-library/present': typeof StudyLibraryPresentIndexRoute;
    '/study-library/reports': typeof StudyLibraryReportsIndexRoute;
    '/ai-center/ai-tools/vsmart-audio': typeof AiCenterAiToolsVsmartAudioIndexRoute;
    '/ai-center/ai-tools/vsmart-chat': typeof AiCenterAiToolsVsmartChatIndexRoute;
    '/ai-center/ai-tools/vsmart-extract': typeof AiCenterAiToolsVsmartExtractIndexRoute;
    '/ai-center/ai-tools/vsmart-feedback': typeof AiCenterAiToolsVsmartFeedbackIndexRoute;
    '/ai-center/ai-tools/vsmart-image': typeof AiCenterAiToolsVsmartImageIndexRoute;
    '/ai-center/ai-tools/vsmart-lecture': typeof AiCenterAiToolsVsmartLectureIndexRoute;
    '/ai-center/ai-tools/vsmart-organizer': typeof AiCenterAiToolsVsmartOrganizerIndexRoute;
    '/ai-center/ai-tools/vsmart-prompt': typeof AiCenterAiToolsVsmartPromptIndexRoute;
    '/ai-center/ai-tools/vsmart-sorter': typeof AiCenterAiToolsVsmartSorterIndexRoute;
    '/ai-center/ai-tools/vsmart-upload': typeof AiCenterAiToolsVsmartUploadIndexRoute;
    '/assessment/export/$assessmentId': typeof AssessmentExportAssessmentIdIndexRoute;
    '/evaluator-ai/assessment/create-assessment': typeof EvaluatorAiAssessmentCreateAssessmentIndexRoute;
    '/evaluator-ai/evaluation/student-summary': typeof EvaluatorAiEvaluationStudentSummaryIndexRoute;
    '/study-library/courses/levels': typeof StudyLibraryCoursesLevelsIndexRoute;
    '/study-library/present/add': typeof StudyLibraryPresentAddIndexRoute;
    '/assessment/create-assessment/$assessmentId/$examtype': typeof AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute;
    '/homework-creation/create-assessment/$assessmentId/$examtype': typeof HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute;
    '/study-library/courses/levels/subjects': typeof StudyLibraryCoursesLevelsSubjectsIndexRoute;
    '/evaluation/evaluate/$assessmentId/$attemptId/$examType': typeof EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute;
    '/study-library/courses/levels/subjects/modules': typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute;
    '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType': typeof EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute;
    '/study-library/courses/levels/subjects/modules/chapters': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute;
    '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab': typeof AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab': typeof HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    '/study-library/courses/levels/subjects/modules/chapters/slides': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/ai-center/': typeof AiCenterIndexRoute;
    '/assessment/': typeof AssessmentIndexRoute;
    '/community/': typeof CommunityIndexRoute;
    '/dashboard/': typeof DashboardIndexRoute;
    '/evaluation/': typeof EvaluationIndexRoute;
    '/evaluator-ai/': typeof EvaluatorAiIndexRoute;
    '/login/': typeof LoginIndexRoute;
    '/manage-institute/': typeof ManageInstituteIndexRoute;
    '/manage-students/': typeof ManageStudentsIndexRoute;
    '/signup/': typeof SignupIndexRoute;
    '/study-library/': typeof StudyLibraryIndexRoute;
    '/ai-center/ai-tools/': typeof AiCenterAiToolsIndexRoute;
    '/assessment/assessment-list/': typeof AssessmentAssessmentListIndexRoute;
    '/assessment/question-papers/': typeof AssessmentQuestionPapersIndexRoute;
    '/community/question-paper/': typeof CommunityQuestionPaperIndexRoute;
    '/evaluation/evaluation-tool/': typeof EvaluationEvaluationToolIndexRoute;
    '/evaluation/evaluations/': typeof EvaluationEvaluationsIndexRoute;
    '/evaluator-ai/assessment/': typeof EvaluatorAiAssessmentIndexRoute;
    '/evaluator-ai/evaluation/': typeof EvaluatorAiEvaluationIndexRoute;
    '/evaluator-ai/students/': typeof EvaluatorAiStudentsIndexRoute;
    '/homework-creation/assessment-list/': typeof HomeworkCreationAssessmentListIndexRoute;
    '/login/$key/': typeof LoginKeyIndexRoute;
    '/login/forgot-password/': typeof LoginForgotPasswordIndexRoute;
    '/manage-institute/batches/': typeof ManageInstituteBatchesIndexRoute;
    '/manage-institute/sessions/': typeof ManageInstituteSessionsIndexRoute;
    '/manage-institute/teams/': typeof ManageInstituteTeamsIndexRoute;
    '/manage-students/enroll-requests/': typeof ManageStudentsEnrollRequestsIndexRoute;
    '/manage-students/invite/': typeof ManageStudentsInviteIndexRoute;
    '/manage-students/students-list/': typeof ManageStudentsStudentsListIndexRoute;
    '/signup/onboarding/': typeof SignupOnboardingIndexRoute;
    '/study-library/courses/': typeof StudyLibraryCoursesIndexRoute;
    '/study-library/present/': typeof StudyLibraryPresentIndexRoute;
    '/study-library/reports/': typeof StudyLibraryReportsIndexRoute;
    '/ai-center/ai-tools/vsmart-audio/': typeof AiCenterAiToolsVsmartAudioIndexRoute;
    '/ai-center/ai-tools/vsmart-chat/': typeof AiCenterAiToolsVsmartChatIndexRoute;
    '/ai-center/ai-tools/vsmart-extract/': typeof AiCenterAiToolsVsmartExtractIndexRoute;
    '/ai-center/ai-tools/vsmart-feedback/': typeof AiCenterAiToolsVsmartFeedbackIndexRoute;
    '/ai-center/ai-tools/vsmart-image/': typeof AiCenterAiToolsVsmartImageIndexRoute;
    '/ai-center/ai-tools/vsmart-lecture/': typeof AiCenterAiToolsVsmartLectureIndexRoute;
    '/ai-center/ai-tools/vsmart-organizer/': typeof AiCenterAiToolsVsmartOrganizerIndexRoute;
    '/ai-center/ai-tools/vsmart-prompt/': typeof AiCenterAiToolsVsmartPromptIndexRoute;
    '/ai-center/ai-tools/vsmart-sorter/': typeof AiCenterAiToolsVsmartSorterIndexRoute;
    '/ai-center/ai-tools/vsmart-upload/': typeof AiCenterAiToolsVsmartUploadIndexRoute;
    '/assessment/export/$assessmentId/': typeof AssessmentExportAssessmentIdIndexRoute;
    '/evaluator-ai/assessment/create-assessment/': typeof EvaluatorAiAssessmentCreateAssessmentIndexRoute;
    '/evaluator-ai/evaluation/student-summary/': typeof EvaluatorAiEvaluationStudentSummaryIndexRoute;
    '/study-library/courses/levels/': typeof StudyLibraryCoursesLevelsIndexRoute;
    '/study-library/present/add/': typeof StudyLibraryPresentAddIndexRoute;
    '/assessment/create-assessment/$assessmentId/$examtype/': typeof AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute;
    '/homework-creation/create-assessment/$assessmentId/$examtype/': typeof HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute;
    '/study-library/courses/levels/subjects/': typeof StudyLibraryCoursesLevelsSubjectsIndexRoute;
    '/evaluation/evaluate/$assessmentId/$attemptId/$examType/': typeof EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute;
    '/study-library/courses/levels/subjects/modules/': typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute;
    '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/': typeof EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute;
    '/study-library/courses/levels/subjects/modules/chapters/': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute;
    '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/': typeof AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/': typeof HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    '/study-library/courses/levels/subjects/modules/chapters/slides/': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/ai-center'
        | '/assessment'
        | '/community'
        | '/dashboard'
        | '/evaluation'
        | '/evaluator-ai'
        | '/login'
        | '/manage-institute'
        | '/manage-students'
        | '/signup'
        | '/study-library'
        | '/ai-center/ai-tools'
        | '/assessment/assessment-list'
        | '/assessment/question-papers'
        | '/community/question-paper'
        | '/evaluation/evaluation-tool'
        | '/evaluation/evaluations'
        | '/evaluator-ai/assessment'
        | '/evaluator-ai/evaluation'
        | '/evaluator-ai/students'
        | '/homework-creation/assessment-list'
        | '/login/$key'
        | '/login/forgot-password'
        | '/manage-institute/batches'
        | '/manage-institute/sessions'
        | '/manage-institute/teams'
        | '/manage-students/enroll-requests'
        | '/manage-students/invite'
        | '/manage-students/students-list'
        | '/signup/onboarding'
        | '/study-library/courses'
        | '/study-library/present'
        | '/study-library/reports'
        | '/ai-center/ai-tools/vsmart-audio'
        | '/ai-center/ai-tools/vsmart-chat'
        | '/ai-center/ai-tools/vsmart-extract'
        | '/ai-center/ai-tools/vsmart-feedback'
        | '/ai-center/ai-tools/vsmart-image'
        | '/ai-center/ai-tools/vsmart-lecture'
        | '/ai-center/ai-tools/vsmart-organizer'
        | '/ai-center/ai-tools/vsmart-prompt'
        | '/ai-center/ai-tools/vsmart-sorter'
        | '/ai-center/ai-tools/vsmart-upload'
        | '/assessment/export/$assessmentId'
        | '/evaluator-ai/assessment/create-assessment'
        | '/evaluator-ai/evaluation/student-summary'
        | '/study-library/courses/levels'
        | '/study-library/present/add'
        | '/assessment/create-assessment/$assessmentId/$examtype'
        | '/homework-creation/create-assessment/$assessmentId/$examtype'
        | '/study-library/courses/levels/subjects'
        | '/evaluation/evaluate/$assessmentId/$attemptId/$examType'
        | '/study-library/courses/levels/subjects/modules'
        | '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType'
        | '/study-library/courses/levels/subjects/modules/chapters'
        | '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab'
        | '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab'
        | '/study-library/courses/levels/subjects/modules/chapters/slides';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/ai-center'
        | '/assessment'
        | '/community'
        | '/dashboard'
        | '/evaluation'
        | '/evaluator-ai'
        | '/login'
        | '/manage-institute'
        | '/manage-students'
        | '/signup'
        | '/study-library'
        | '/ai-center/ai-tools'
        | '/assessment/assessment-list'
        | '/assessment/question-papers'
        | '/community/question-paper'
        | '/evaluation/evaluation-tool'
        | '/evaluation/evaluations'
        | '/evaluator-ai/assessment'
        | '/evaluator-ai/evaluation'
        | '/evaluator-ai/students'
        | '/homework-creation/assessment-list'
        | '/login/$key'
        | '/login/forgot-password'
        | '/manage-institute/batches'
        | '/manage-institute/sessions'
        | '/manage-institute/teams'
        | '/manage-students/enroll-requests'
        | '/manage-students/invite'
        | '/manage-students/students-list'
        | '/signup/onboarding'
        | '/study-library/courses'
        | '/study-library/present'
        | '/study-library/reports'
        | '/ai-center/ai-tools/vsmart-audio'
        | '/ai-center/ai-tools/vsmart-chat'
        | '/ai-center/ai-tools/vsmart-extract'
        | '/ai-center/ai-tools/vsmart-feedback'
        | '/ai-center/ai-tools/vsmart-image'
        | '/ai-center/ai-tools/vsmart-lecture'
        | '/ai-center/ai-tools/vsmart-organizer'
        | '/ai-center/ai-tools/vsmart-prompt'
        | '/ai-center/ai-tools/vsmart-sorter'
        | '/ai-center/ai-tools/vsmart-upload'
        | '/assessment/export/$assessmentId'
        | '/evaluator-ai/assessment/create-assessment'
        | '/evaluator-ai/evaluation/student-summary'
        | '/study-library/courses/levels'
        | '/study-library/present/add'
        | '/assessment/create-assessment/$assessmentId/$examtype'
        | '/homework-creation/create-assessment/$assessmentId/$examtype'
        | '/study-library/courses/levels/subjects'
        | '/evaluation/evaluate/$assessmentId/$attemptId/$examType'
        | '/study-library/courses/levels/subjects/modules'
        | '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType'
        | '/study-library/courses/levels/subjects/modules/chapters'
        | '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab'
        | '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab'
        | '/study-library/courses/levels/subjects/modules/chapters/slides';
    id:
        | '__root__'
        | '/ai-center/'
        | '/assessment/'
        | '/community/'
        | '/dashboard/'
        | '/evaluation/'
        | '/evaluator-ai/'
        | '/login/'
        | '/manage-institute/'
        | '/manage-students/'
        | '/signup/'
        | '/study-library/'
        | '/ai-center/ai-tools/'
        | '/assessment/assessment-list/'
        | '/assessment/question-papers/'
        | '/community/question-paper/'
        | '/evaluation/evaluation-tool/'
        | '/evaluation/evaluations/'
        | '/evaluator-ai/assessment/'
        | '/evaluator-ai/evaluation/'
        | '/evaluator-ai/students/'
        | '/homework-creation/assessment-list/'
        | '/login/$key/'
        | '/login/forgot-password/'
        | '/manage-institute/batches/'
        | '/manage-institute/sessions/'
        | '/manage-institute/teams/'
        | '/manage-students/enroll-requests/'
        | '/manage-students/invite/'
        | '/manage-students/students-list/'
        | '/signup/onboarding/'
        | '/study-library/courses/'
        | '/study-library/present/'
        | '/study-library/reports/'
        | '/ai-center/ai-tools/vsmart-audio/'
        | '/ai-center/ai-tools/vsmart-chat/'
        | '/ai-center/ai-tools/vsmart-extract/'
        | '/ai-center/ai-tools/vsmart-feedback/'
        | '/ai-center/ai-tools/vsmart-image/'
        | '/ai-center/ai-tools/vsmart-lecture/'
        | '/ai-center/ai-tools/vsmart-organizer/'
        | '/ai-center/ai-tools/vsmart-prompt/'
        | '/ai-center/ai-tools/vsmart-sorter/'
        | '/ai-center/ai-tools/vsmart-upload/'
        | '/assessment/export/$assessmentId/'
        | '/evaluator-ai/assessment/create-assessment/'
        | '/evaluator-ai/evaluation/student-summary/'
        | '/study-library/courses/levels/'
        | '/study-library/present/add/'
        | '/assessment/create-assessment/$assessmentId/$examtype/'
        | '/homework-creation/create-assessment/$assessmentId/$examtype/'
        | '/study-library/courses/levels/subjects/'
        | '/evaluation/evaluate/$assessmentId/$attemptId/$examType/'
        | '/study-library/courses/levels/subjects/modules/'
        | '/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/'
        | '/study-library/courses/levels/subjects/modules/chapters/'
        | '/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/'
        | '/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/'
        | '/study-library/courses/levels/subjects/modules/chapters/slides/';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    AiCenterIndexRoute: typeof AiCenterIndexRoute;
    AssessmentIndexRoute: typeof AssessmentIndexRoute;
    CommunityIndexRoute: typeof CommunityIndexRoute;
    DashboardIndexRoute: typeof DashboardIndexRoute;
    EvaluationIndexRoute: typeof EvaluationIndexRoute;
    EvaluatorAiIndexRoute: typeof EvaluatorAiIndexRoute;
    LoginIndexRoute: typeof LoginIndexRoute;
    ManageInstituteIndexRoute: typeof ManageInstituteIndexRoute;
    ManageStudentsIndexRoute: typeof ManageStudentsIndexRoute;
    SignupIndexRoute: typeof SignupIndexRoute;
    StudyLibraryIndexRoute: typeof StudyLibraryIndexRoute;
    AiCenterAiToolsIndexRoute: typeof AiCenterAiToolsIndexRoute;
    AssessmentAssessmentListIndexRoute: typeof AssessmentAssessmentListIndexRoute;
    AssessmentQuestionPapersIndexRoute: typeof AssessmentQuestionPapersIndexRoute;
    CommunityQuestionPaperIndexRoute: typeof CommunityQuestionPaperIndexRoute;
    EvaluationEvaluationToolIndexRoute: typeof EvaluationEvaluationToolIndexRoute;
    EvaluationEvaluationsIndexRoute: typeof EvaluationEvaluationsIndexRoute;
    EvaluatorAiAssessmentIndexRoute: typeof EvaluatorAiAssessmentIndexRoute;
    EvaluatorAiEvaluationIndexRoute: typeof EvaluatorAiEvaluationIndexRoute;
    EvaluatorAiStudentsIndexRoute: typeof EvaluatorAiStudentsIndexRoute;
    HomeworkCreationAssessmentListIndexRoute: typeof HomeworkCreationAssessmentListIndexRoute;
    LoginKeyIndexRoute: typeof LoginKeyIndexRoute;
    LoginForgotPasswordIndexRoute: typeof LoginForgotPasswordIndexRoute;
    ManageInstituteBatchesIndexRoute: typeof ManageInstituteBatchesIndexRoute;
    ManageInstituteSessionsIndexRoute: typeof ManageInstituteSessionsIndexRoute;
    ManageInstituteTeamsIndexRoute: typeof ManageInstituteTeamsIndexRoute;
    ManageStudentsEnrollRequestsIndexRoute: typeof ManageStudentsEnrollRequestsIndexRoute;
    ManageStudentsInviteIndexRoute: typeof ManageStudentsInviteIndexRoute;
    ManageStudentsStudentsListIndexRoute: typeof ManageStudentsStudentsListIndexRoute;
    SignupOnboardingIndexRoute: typeof SignupOnboardingIndexRoute;
    StudyLibraryCoursesIndexRoute: typeof StudyLibraryCoursesIndexRoute;
    StudyLibraryPresentIndexRoute: typeof StudyLibraryPresentIndexRoute;
    StudyLibraryReportsIndexRoute: typeof StudyLibraryReportsIndexRoute;
    AiCenterAiToolsVsmartAudioIndexRoute: typeof AiCenterAiToolsVsmartAudioIndexRoute;
    AiCenterAiToolsVsmartChatIndexRoute: typeof AiCenterAiToolsVsmartChatIndexRoute;
    AiCenterAiToolsVsmartExtractIndexRoute: typeof AiCenterAiToolsVsmartExtractIndexRoute;
    AiCenterAiToolsVsmartFeedbackIndexRoute: typeof AiCenterAiToolsVsmartFeedbackIndexRoute;
    AiCenterAiToolsVsmartImageIndexRoute: typeof AiCenterAiToolsVsmartImageIndexRoute;
    AiCenterAiToolsVsmartLectureIndexRoute: typeof AiCenterAiToolsVsmartLectureIndexRoute;
    AiCenterAiToolsVsmartOrganizerIndexRoute: typeof AiCenterAiToolsVsmartOrganizerIndexRoute;
    AiCenterAiToolsVsmartPromptIndexRoute: typeof AiCenterAiToolsVsmartPromptIndexRoute;
    AiCenterAiToolsVsmartSorterIndexRoute: typeof AiCenterAiToolsVsmartSorterIndexRoute;
    AiCenterAiToolsVsmartUploadIndexRoute: typeof AiCenterAiToolsVsmartUploadIndexRoute;
    AssessmentExportAssessmentIdIndexRoute: typeof AssessmentExportAssessmentIdIndexRoute;
    EvaluatorAiAssessmentCreateAssessmentIndexRoute: typeof EvaluatorAiAssessmentCreateAssessmentIndexRoute;
    EvaluatorAiEvaluationStudentSummaryIndexRoute: typeof EvaluatorAiEvaluationStudentSummaryIndexRoute;
    StudyLibraryCoursesLevelsIndexRoute: typeof StudyLibraryCoursesLevelsIndexRoute;
    StudyLibraryPresentAddIndexRoute: typeof StudyLibraryPresentAddIndexRoute;
    AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute: typeof AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute;
    HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute: typeof HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute;
    StudyLibraryCoursesLevelsSubjectsIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsIndexRoute;
    EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute: typeof EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute;
    StudyLibraryCoursesLevelsSubjectsModulesIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute;
    EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute: typeof EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute;
    StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute;
    AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute: typeof AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute: typeof HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute;
    StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
    AiCenterIndexRoute: AiCenterIndexRoute,
    AssessmentIndexRoute: AssessmentIndexRoute,
    CommunityIndexRoute: CommunityIndexRoute,
    DashboardIndexRoute: DashboardIndexRoute,
    EvaluationIndexRoute: EvaluationIndexRoute,
    EvaluatorAiIndexRoute: EvaluatorAiIndexRoute,
    LoginIndexRoute: LoginIndexRoute,
    ManageInstituteIndexRoute: ManageInstituteIndexRoute,
    ManageStudentsIndexRoute: ManageStudentsIndexRoute,
    SignupIndexRoute: SignupIndexRoute,
    StudyLibraryIndexRoute: StudyLibraryIndexRoute,
    AiCenterAiToolsIndexRoute: AiCenterAiToolsIndexRoute,
    AssessmentAssessmentListIndexRoute: AssessmentAssessmentListIndexRoute,
    AssessmentQuestionPapersIndexRoute: AssessmentQuestionPapersIndexRoute,
    CommunityQuestionPaperIndexRoute: CommunityQuestionPaperIndexRoute,
    EvaluationEvaluationToolIndexRoute: EvaluationEvaluationToolIndexRoute,
    EvaluationEvaluationsIndexRoute: EvaluationEvaluationsIndexRoute,
    EvaluatorAiAssessmentIndexRoute: EvaluatorAiAssessmentIndexRoute,
    EvaluatorAiEvaluationIndexRoute: EvaluatorAiEvaluationIndexRoute,
    EvaluatorAiStudentsIndexRoute: EvaluatorAiStudentsIndexRoute,
    HomeworkCreationAssessmentListIndexRoute: HomeworkCreationAssessmentListIndexRoute,
    LoginKeyIndexRoute: LoginKeyIndexRoute,
    LoginForgotPasswordIndexRoute: LoginForgotPasswordIndexRoute,
    ManageInstituteBatchesIndexRoute: ManageInstituteBatchesIndexRoute,
    ManageInstituteSessionsIndexRoute: ManageInstituteSessionsIndexRoute,
    ManageInstituteTeamsIndexRoute: ManageInstituteTeamsIndexRoute,
    ManageStudentsEnrollRequestsIndexRoute: ManageStudentsEnrollRequestsIndexRoute,
    ManageStudentsInviteIndexRoute: ManageStudentsInviteIndexRoute,
    ManageStudentsStudentsListIndexRoute: ManageStudentsStudentsListIndexRoute,
    SignupOnboardingIndexRoute: SignupOnboardingIndexRoute,
    StudyLibraryCoursesIndexRoute: StudyLibraryCoursesIndexRoute,
    StudyLibraryPresentIndexRoute: StudyLibraryPresentIndexRoute,
    StudyLibraryReportsIndexRoute: StudyLibraryReportsIndexRoute,
    AiCenterAiToolsVsmartAudioIndexRoute: AiCenterAiToolsVsmartAudioIndexRoute,
    AiCenterAiToolsVsmartChatIndexRoute: AiCenterAiToolsVsmartChatIndexRoute,
    AiCenterAiToolsVsmartExtractIndexRoute: AiCenterAiToolsVsmartExtractIndexRoute,
    AiCenterAiToolsVsmartFeedbackIndexRoute: AiCenterAiToolsVsmartFeedbackIndexRoute,
    AiCenterAiToolsVsmartImageIndexRoute: AiCenterAiToolsVsmartImageIndexRoute,
    AiCenterAiToolsVsmartLectureIndexRoute: AiCenterAiToolsVsmartLectureIndexRoute,
    AiCenterAiToolsVsmartOrganizerIndexRoute: AiCenterAiToolsVsmartOrganizerIndexRoute,
    AiCenterAiToolsVsmartPromptIndexRoute: AiCenterAiToolsVsmartPromptIndexRoute,
    AiCenterAiToolsVsmartSorterIndexRoute: AiCenterAiToolsVsmartSorterIndexRoute,
    AiCenterAiToolsVsmartUploadIndexRoute: AiCenterAiToolsVsmartUploadIndexRoute,
    AssessmentExportAssessmentIdIndexRoute: AssessmentExportAssessmentIdIndexRoute,
    EvaluatorAiAssessmentCreateAssessmentIndexRoute:
        EvaluatorAiAssessmentCreateAssessmentIndexRoute,
    EvaluatorAiEvaluationStudentSummaryIndexRoute: EvaluatorAiEvaluationStudentSummaryIndexRoute,
    StudyLibraryCoursesLevelsIndexRoute: StudyLibraryCoursesLevelsIndexRoute,
    StudyLibraryPresentAddIndexRoute: StudyLibraryPresentAddIndexRoute,
    AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute:
        AssessmentCreateAssessmentAssessmentIdExamtypeIndexRoute,
    HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute:
        HomeworkCreationCreateAssessmentAssessmentIdExamtypeIndexRoute,
    StudyLibraryCoursesLevelsSubjectsIndexRoute: StudyLibraryCoursesLevelsSubjectsIndexRoute,
    EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute:
        EvaluationEvaluateAssessmentIdAttemptIdExamTypeIndexRoute,
    StudyLibraryCoursesLevelsSubjectsModulesIndexRoute:
        StudyLibraryCoursesLevelsSubjectsModulesIndexRoute,
    EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute:
        EvaluationEvaluationsAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeIndexRoute,
    StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute:
        StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute,
    AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute:
        AssessmentAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute,
    HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute:
        HomeworkCreationAssessmentListAssessmentDetailsAssessmentIdExamTypeAssesssmentTypeAssessmentTabIndexRoute,
    StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute:
        StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ai-center/",
        "/assessment/",
        "/community/",
        "/dashboard/",
        "/evaluation/",
        "/evaluator-ai/",
        "/login/",
        "/manage-institute/",
        "/manage-students/",
        "/signup/",
        "/study-library/",
        "/ai-center/ai-tools/",
        "/assessment/assessment-list/",
        "/assessment/question-papers/",
        "/community/question-paper/",
        "/evaluation/evaluation-tool/",
        "/evaluation/evaluations/",
        "/evaluator-ai/assessment/",
        "/evaluator-ai/evaluation/",
        "/evaluator-ai/students/",
        "/homework-creation/assessment-list/",
        "/login/$key/",
        "/login/forgot-password/",
        "/manage-institute/batches/",
        "/manage-institute/sessions/",
        "/manage-institute/teams/",
        "/manage-students/enroll-requests/",
        "/manage-students/invite/",
        "/manage-students/students-list/",
        "/signup/onboarding/",
        "/study-library/courses/",
        "/study-library/present/",
        "/study-library/reports/",
        "/ai-center/ai-tools/vsmart-audio/",
        "/ai-center/ai-tools/vsmart-chat/",
        "/ai-center/ai-tools/vsmart-extract/",
        "/ai-center/ai-tools/vsmart-feedback/",
        "/ai-center/ai-tools/vsmart-image/",
        "/ai-center/ai-tools/vsmart-lecture/",
        "/ai-center/ai-tools/vsmart-organizer/",
        "/ai-center/ai-tools/vsmart-prompt/",
        "/ai-center/ai-tools/vsmart-sorter/",
        "/ai-center/ai-tools/vsmart-upload/",
        "/assessment/export/$assessmentId/",
        "/evaluator-ai/assessment/create-assessment/",
        "/evaluator-ai/evaluation/student-summary/",
        "/study-library/courses/levels/",
        "/study-library/present/add/",
        "/assessment/create-assessment/$assessmentId/$examtype/",
        "/homework-creation/create-assessment/$assessmentId/$examtype/",
        "/study-library/courses/levels/subjects/",
        "/evaluation/evaluate/$assessmentId/$attemptId/$examType/",
        "/study-library/courses/levels/subjects/modules/",
        "/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/",
        "/study-library/courses/levels/subjects/modules/chapters/",
        "/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/",
        "/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/",
        "/study-library/courses/levels/subjects/modules/chapters/slides/"
      ]
    },
    "/ai-center/": {
      "filePath": "ai-center/index.tsx"
    },
    "/assessment/": {
      "filePath": "assessment/index.tsx"
    },
    "/community/": {
      "filePath": "community/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/evaluation/": {
      "filePath": "evaluation/index.tsx"
    },
    "/evaluator-ai/": {
      "filePath": "evaluator-ai/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/manage-institute/": {
      "filePath": "manage-institute/index.tsx"
    },
    "/manage-students/": {
      "filePath": "manage-students/index.tsx"
    },
    "/signup/": {
      "filePath": "signup/index.tsx"
    },
    "/study-library/": {
      "filePath": "study-library/index.tsx"
    },
    "/ai-center/ai-tools/": {
      "filePath": "ai-center/ai-tools/index.tsx"
    },
    "/assessment/assessment-list/": {
      "filePath": "assessment/assessment-list/index.tsx"
    },
    "/assessment/question-papers/": {
      "filePath": "assessment/question-papers/index.tsx"
    },
    "/community/question-paper/": {
      "filePath": "community/question-paper/index.tsx"
    },
    "/evaluation/evaluation-tool/": {
      "filePath": "evaluation/evaluation-tool/index.tsx"
    },
    "/evaluation/evaluations/": {
      "filePath": "evaluation/evaluations/index.tsx"
    },
    "/evaluator-ai/assessment/": {
      "filePath": "evaluator-ai/assessment/index.tsx"
    },
    "/evaluator-ai/evaluation/": {
      "filePath": "evaluator-ai/evaluation/index.tsx"
    },
    "/evaluator-ai/students/": {
      "filePath": "evaluator-ai/students/index.tsx"
    },
    "/homework-creation/assessment-list/": {
      "filePath": "homework-creation/assessment-list/index.tsx"
    },
    "/login/$key/": {
      "filePath": "login/$key/index.tsx"
    },
    "/login/forgot-password/": {
      "filePath": "login/forgot-password/index.tsx"
    },
    "/manage-institute/batches/": {
      "filePath": "manage-institute/batches/index.tsx"
    },
    "/manage-institute/sessions/": {
      "filePath": "manage-institute/sessions/index.tsx"
    },
    "/manage-institute/teams/": {
      "filePath": "manage-institute/teams/index.tsx"
    },
    "/manage-students/enroll-requests/": {
      "filePath": "manage-students/enroll-requests/index.tsx"
    },
    "/manage-students/invite/": {
      "filePath": "manage-students/invite/index.tsx"
    },
    "/manage-students/students-list/": {
      "filePath": "manage-students/students-list/index.tsx"
    },
    "/signup/onboarding/": {
      "filePath": "signup/onboarding/index.tsx"
    },
    "/study-library/courses/": {
      "filePath": "study-library/courses/index.tsx"
    },
    "/study-library/present/": {
      "filePath": "study-library/present/index.tsx"
    },
    "/study-library/reports/": {
      "filePath": "study-library/reports/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-audio/": {
      "filePath": "ai-center/ai-tools/vsmart-audio/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-chat/": {
      "filePath": "ai-center/ai-tools/vsmart-chat/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-extract/": {
      "filePath": "ai-center/ai-tools/vsmart-extract/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-feedback/": {
      "filePath": "ai-center/ai-tools/vsmart-feedback/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-image/": {
      "filePath": "ai-center/ai-tools/vsmart-image/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-lecture/": {
      "filePath": "ai-center/ai-tools/vsmart-lecture/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-organizer/": {
      "filePath": "ai-center/ai-tools/vsmart-organizer/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-prompt/": {
      "filePath": "ai-center/ai-tools/vsmart-prompt/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-sorter/": {
      "filePath": "ai-center/ai-tools/vsmart-sorter/index.tsx"
    },
    "/ai-center/ai-tools/vsmart-upload/": {
      "filePath": "ai-center/ai-tools/vsmart-upload/index.tsx"
    },
    "/assessment/export/$assessmentId/": {
      "filePath": "assessment/export/$assessmentId/index.tsx"
    },
    "/evaluator-ai/assessment/create-assessment/": {
      "filePath": "evaluator-ai/assessment/create-assessment/index.tsx"
    },
    "/evaluator-ai/evaluation/student-summary/": {
      "filePath": "evaluator-ai/evaluation/student-summary/index.tsx"
    },
    "/study-library/courses/levels/": {
      "filePath": "study-library/courses/levels/index.tsx"
    },
    "/study-library/present/add/": {
      "filePath": "study-library/present/add/index.tsx"
    },
    "/assessment/create-assessment/$assessmentId/$examtype/": {
      "filePath": "assessment/create-assessment/$assessmentId/$examtype/index.tsx"
    },
    "/homework-creation/create-assessment/$assessmentId/$examtype/": {
      "filePath": "homework-creation/create-assessment/$assessmentId/$examtype/index.tsx"
    },
    "/study-library/courses/levels/subjects/": {
      "filePath": "study-library/courses/levels/subjects/index.tsx"
    },
    "/evaluation/evaluate/$assessmentId/$attemptId/$examType/": {
      "filePath": "evaluation/evaluate/$assessmentId/$attemptId/$examType/index.tsx"
    },
    "/study-library/courses/levels/subjects/modules/": {
      "filePath": "study-library/courses/levels/subjects/modules/index.tsx"
    },
    "/evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/": {
      "filePath": "evaluation/evaluations/assessment-details/$assessmentId/$examType/$assesssmentType/index.tsx"
    },
    "/study-library/courses/levels/subjects/modules/chapters/": {
      "filePath": "study-library/courses/levels/subjects/modules/chapters/index.tsx"
    },
    "/assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/": {
      "filePath": "assessment/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/index.tsx"
    },
    "/homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/": {
      "filePath": "homework-creation/assessment-list/assessment-details/$assessmentId/$examType/$assesssmentType/$assessmentTab/index.tsx"
    },
    "/study-library/courses/levels/subjects/modules/chapters/slides/": {
      "filePath": "study-library/courses/levels/subjects/modules/chapters/slides/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
