package vacademy.io.admin_core_service.features.learner_operation.enums;

public enum LearnerOperationEnum {
    VIDEO_LAST_TIMESTAMP,
    DOCUMENT_LAST_PAGE,
    PERCENTAGE_DOCUMENT_WATCHED,
    PERCENTAGE_VIDEO_WATCHED,
    MARKED_AS_WATCHED,
    MARKED_FOR_REVIEW,
    PERCENTAGE_CHAPTER_COMPLETED,
    LAST_SLIDE_VIEWED,
    PERCENTAGE_QUESTION_COMPLETED,
    PERCENTAGE_ASSIGNMENT_COMPLETED,
    PERCENTAGE_MODULE_COMPLETED,
    PERCENTAGE_SUBJECT_COMPLETED,
    PERCENTAGE_PACKAGE_SESSION_COMPLETED
}
