import { tableType } from "../../schema/table-schema";

export const useTable = () => {
    return TableDummyData;
};

const TableDummyData: tableType[] = [
    {
        id: "1",
        studentName: "John Doe",
        batch: "10th Premium Pro Group 1",
        enrollmentNumber: "EN001",
        collegeSchool: "ABC University",
        gender: "Male",
        mobileNumber: "1234567890",
        emailId: "john.doe@email.com",
        fatherName: "James Doe",
        motherName: "Jane Doe",
        guardianName: "James Doe",
        guardianNumber: "9876543210",
        guardianEmail: "james.doe@email.com",
        city: "New York",
        state: "NY",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
    {
        id: "2",
        studentName: "Sarah Smith",
        batch: "10th Premium Pro Group 2",
        enrollmentNumber: "EN002",
        collegeSchool: "XYZ College",
        gender: "Female",
        mobileNumber: "2345678901",
        emailId: "sarah.smith@email.com",
        fatherName: "Mike Smith",
        motherName: "Lisa Smith",
        guardianName: "Mike Smith",
        guardianNumber: "8765432109",
        guardianEmail: "mike.smith@email.com",
        city: "Los Angeles",
        state: "CA",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
    {
        id: "3",
        studentName: "Michael Johnson",
        batch: "10th Premium Pro Group 2",
        enrollmentNumber: "EN003",
        collegeSchool: "PQR Institute",
        gender: "Male",
        mobileNumber: "3456789012",
        emailId: "michael.j@email.com",
        fatherName: "Robert Johnson",
        motherName: "Mary Johnson",
        guardianName: "Robert Johnson",
        guardianNumber: "7654321098",
        guardianEmail: "robert.j@email.com",
        city: "Chicago",
        state: "IL",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
    {
        id: "4",
        studentName: "Emily Brown",
        batch: "9th Premium Plus Group 1",
        enrollmentNumber: "EN004",
        collegeSchool: "LMN College",
        gender: "Female",
        mobileNumber: "4567890123",
        emailId: "emily.b@email.com",
        fatherName: "David Brown",
        motherName: "Susan Brown",
        guardianName: "David Brown",
        guardianNumber: "6543210987",
        guardianEmail: "david.b@email.com",
        city: "Houston",
        state: "TX",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
    {
        id: "5",
        studentName: "John Doe",
        batch: "9th Premium Plus Group 1",
        enrollmentNumber: "EN001",
        collegeSchool: "ABC University",
        gender: "Male",
        mobileNumber: "1234567890",
        emailId: "john.doe@email.com",
        fatherName: "James Doe",
        motherName: "Jane Doe",
        guardianName: "James Doe",
        guardianNumber: "9876543210",
        guardianEmail: "james.doe@email.com",
        city: "New York",
        state: "NY",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
    {
        id: "6",
        studentName: "Sarah Smith",
        batch: "9th Premium Plus Group 1",
        enrollmentNumber: "EN002",
        collegeSchool: "XYZ College",
        gender: "Female",
        mobileNumber: "2345678901",
        emailId: "sarah.smith@email.com",
        fatherName: "Mike Smith",
        motherName: "Lisa Smith",
        guardianName: "Mike Smith",
        guardianNumber: "8765432109",
        guardianEmail: "mike.smith@email.com",
        city: "Los Angeles",
        state: "CA",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
    {
        id: "7",
        studentName: "Michael Johnson",
        batch: "10th Premium Plus Group 2",
        enrollmentNumber: "EN003",
        collegeSchool: "PQR Institute",
        gender: "Male",
        mobileNumber: "3456789012",
        emailId: "michael.j@email.com",
        fatherName: "Robert Johnson",
        motherName: "Mary Johnson",
        guardianName: "Robert Johnson",
        guardianNumber: "7654321098",
        guardianEmail: "robert.j@email.com",
        city: "Chicago",
        state: "IL",
        sessionExpiry: "2024-12-31",
        status: "active",
    },
];

export const filters = [
    {
        id: "batch",
        label: "Batches",
        filters: [
            "10th Premium Pro Group 1",
            "10th Premium Pro Group 2",
            "10th Premium Plus Group 1",
            "10th Premium Plus Group 2",
            "9th Premium Pro Group 1",
            "9th Premium Pro Group 2",
            "9th Premium Plus Group 1",
            "9th Premium Plus Group 2",
        ],
    },
    {
        id: "status",
        label: "Status",
        filters: ["active", "inactive"],
    },
    {
        id: "gender",
        label: "Gender",
        filters: ["Male", "Female", "Others"],
    },
    {
        id: "sessionExpiry",
        label: "Session Expiry",
        filters: ["Above Session Threshold", "Below Session Threshold", "Session Expired"],
    },
];

export const sessionlist = ["2024-2025", "2023-2024", "2022-2023", "2021-2022", "2020-2021"];
