/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileIndexRouteImport } from './routes/user-profile/index'
import { Route as TermsAndConditionsIndexRouteImport } from './routes/terms-and-conditions/index'
import { Route as StudyLibraryIndexRouteImport } from './routes/study-library/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ReferralIndexRouteImport } from './routes/referral/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LiveClassGuestIndexRouteImport } from './routes/live-class-guest/index'
import { Route as LearnerInvitationResponseIndexRouteImport } from './routes/learner-invitation-response/index'
import { Route as InstituteSelectionIndexRouteImport } from './routes/institute-selection/index'
import { Route as DeleteUserIndexRouteImport } from './routes/delete-user/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChangePasswordIndexRouteImport } from './routes/change-password/index'
import { Route as SessionSelectionPageIndexRouteImport } from './routes/SessionSelectionPage/index'
import { Route as UserProfileEditIndexRouteImport } from './routes/user-profile/edit/index'
import { Route as StudyLibraryLiveClassIndexRouteImport } from './routes/study-library/live-class/index'
import { Route as StudyLibraryCoursesIndexRouteImport } from './routes/study-library/courses/index'
import { Route as RegisterLiveClassIndexRouteImport } from './routes/register/live-class/index'
import { Route as LoginForgotPasswordIndexRouteImport } from './routes/login/forgot-password/index'
import { Route as LiveClassGuestWaitingRoomIndexRouteImport } from './routes/live-class-guest/waiting-room/index'
import { Route as LiveClassGuestEmbedIndexRouteImport } from './routes/live-class-guest/embed/index'
import { Route as HomeworkReportsIndexRouteImport } from './routes/homework/reports/index'
import { Route as HomeworkListIndexRouteImport } from './routes/homework/list/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard/notifications/index'
import { Route as AssessmentReportsIndexRouteImport } from './routes/assessment/reports/index'
import { Route as AssessmentExaminationIndexRouteImport } from './routes/assessment/examination/index'
import { Route as StudyLibraryLiveClassWaitingRoomIndexRouteImport } from './routes/study-library/live-class/waiting-room/index'
import { Route as StudyLibraryLiveClassEmbedIndexRouteImport } from './routes/study-library/live-class/embed/index'
import { Route as StudyLibraryCoursesLevelsIndexRouteImport } from './routes/study-library/courses/levels/index'
import { Route as AssessmentReportsStudentReportIndexRouteImport } from './routes/assessment/reports/student-report/index'
import { Route as AssessmentExaminationAssessmentIdIndexRouteImport } from './routes/assessment/examination/$assessmentId/index'
import { Route as AssessmentExaminationAssessmentIdAssessmentPreviewRouteImport } from './routes/assessment/examination/$assessmentId/assessmentPreview'
import { Route as AssessmentExaminationAssessmentIdLearnerLiveTestRouteImport } from './routes/assessment/examination/$assessmentId/LearnerLiveTest'
import { Route as StudyLibraryCoursesLevelsSubjectsIndexRouteImport } from './routes/study-library/courses/levels/subjects/index'
import { Route as StudyLibraryCoursesLevelsSubjectsModulesIndexRouteImport } from './routes/study-library/courses/levels/subjects/modules/index'
import { Route as StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRouteImport } from './routes/study-library/courses/levels/subjects/modules/chapters/index'
import { Route as StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRouteImport } from './routes/study-library/courses/levels/subjects/modules/chapters/slides/index'

const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/user-profile/',
  path: '/user-profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsIndexRoute = TermsAndConditionsIndexRouteImport.update({
  id: '/terms-and-conditions/',
  path: '/terms-and-conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyLibraryIndexRoute = StudyLibraryIndexRouteImport.update({
  id: '/study-library/',
  path: '/study-library/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralIndexRoute = ReferralIndexRouteImport.update({
  id: '/referral/',
  path: '/referral/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassGuestIndexRoute = LiveClassGuestIndexRouteImport.update({
  id: '/live-class-guest/',
  path: '/live-class-guest/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerInvitationResponseIndexRoute =
  LearnerInvitationResponseIndexRouteImport.update({
    id: '/learner-invitation-response/',
    path: '/learner-invitation-response/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstituteSelectionIndexRoute = InstituteSelectionIndexRouteImport.update({
  id: '/institute-selection/',
  path: '/institute-selection/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteUserIndexRoute = DeleteUserIndexRouteImport.update({
  id: '/delete-user/',
  path: '/delete-user/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordIndexRoute = ChangePasswordIndexRouteImport.update({
  id: '/change-password/',
  path: '/change-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSelectionPageIndexRoute =
  SessionSelectionPageIndexRouteImport.update({
    id: '/SessionSelectionPage/',
    path: '/SessionSelectionPage/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserProfileEditIndexRoute = UserProfileEditIndexRouteImport.update({
  id: '/user-profile/edit/',
  path: '/user-profile/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyLibraryLiveClassIndexRoute =
  StudyLibraryLiveClassIndexRouteImport.update({
    id: '/study-library/live-class/',
    path: '/study-library/live-class/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryCoursesIndexRoute =
  StudyLibraryCoursesIndexRouteImport.update({
    id: '/study-library/courses/',
    path: '/study-library/courses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterLiveClassIndexRoute = RegisterLiveClassIndexRouteImport.update({
  id: '/register/live-class/',
  path: '/register/live-class/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginForgotPasswordIndexRoute =
  LoginForgotPasswordIndexRouteImport.update({
    id: '/login/forgot-password/',
    path: '/login/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiveClassGuestWaitingRoomIndexRoute =
  LiveClassGuestWaitingRoomIndexRouteImport.update({
    id: '/live-class-guest/waiting-room/',
    path: '/live-class-guest/waiting-room/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiveClassGuestEmbedIndexRoute =
  LiveClassGuestEmbedIndexRouteImport.update({
    id: '/live-class-guest/embed/',
    path: '/live-class-guest/embed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HomeworkReportsIndexRoute = HomeworkReportsIndexRouteImport.update({
  id: '/homework/reports/',
  path: '/homework/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkListIndexRoute = HomeworkListIndexRouteImport.update({
  id: '/homework/list/',
  path: '/homework/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/dashboard/notifications/',
    path: '/dashboard/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentReportsIndexRoute = AssessmentReportsIndexRouteImport.update({
  id: '/assessment/reports/',
  path: '/assessment/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentExaminationIndexRoute =
  AssessmentExaminationIndexRouteImport.update({
    id: '/assessment/examination/',
    path: '/assessment/examination/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryLiveClassWaitingRoomIndexRoute =
  StudyLibraryLiveClassWaitingRoomIndexRouteImport.update({
    id: '/study-library/live-class/waiting-room/',
    path: '/study-library/live-class/waiting-room/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryLiveClassEmbedIndexRoute =
  StudyLibraryLiveClassEmbedIndexRouteImport.update({
    id: '/study-library/live-class/embed/',
    path: '/study-library/live-class/embed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryCoursesLevelsIndexRoute =
  StudyLibraryCoursesLevelsIndexRouteImport.update({
    id: '/study-library/courses/levels/',
    path: '/study-library/courses/levels/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentReportsStudentReportIndexRoute =
  AssessmentReportsStudentReportIndexRouteImport.update({
    id: '/assessment/reports/student-report/',
    path: '/assessment/reports/student-report/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentExaminationAssessmentIdIndexRoute =
  AssessmentExaminationAssessmentIdIndexRouteImport.update({
    id: '/assessment/examination/$assessmentId/',
    path: '/assessment/examination/$assessmentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentExaminationAssessmentIdAssessmentPreviewRoute =
  AssessmentExaminationAssessmentIdAssessmentPreviewRouteImport.update({
    id: '/assessment/examination/$assessmentId/assessmentPreview',
    path: '/assessment/examination/$assessmentId/assessmentPreview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentExaminationAssessmentIdLearnerLiveTestRoute =
  AssessmentExaminationAssessmentIdLearnerLiveTestRouteImport.update({
    id: '/assessment/examination/$assessmentId/LearnerLiveTest',
    path: '/assessment/examination/$assessmentId/LearnerLiveTest',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryCoursesLevelsSubjectsIndexRoute =
  StudyLibraryCoursesLevelsSubjectsIndexRouteImport.update({
    id: '/study-library/courses/levels/subjects/',
    path: '/study-library/courses/levels/subjects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryCoursesLevelsSubjectsModulesIndexRoute =
  StudyLibraryCoursesLevelsSubjectsModulesIndexRouteImport.update({
    id: '/study-library/courses/levels/subjects/modules/',
    path: '/study-library/courses/levels/subjects/modules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute =
  StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRouteImport.update({
    id: '/study-library/courses/levels/subjects/modules/chapters/',
    path: '/study-library/courses/levels/subjects/modules/chapters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute =
  StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRouteImport.update(
    {
      id: '/study-library/courses/levels/subjects/modules/chapters/slides/',
      path: '/study-library/courses/levels/subjects/modules/chapters/slides/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/SessionSelectionPage': typeof SessionSelectionPageIndexRoute
  '/change-password': typeof ChangePasswordIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/delete-user': typeof DeleteUserIndexRoute
  '/institute-selection': typeof InstituteSelectionIndexRoute
  '/learner-invitation-response': typeof LearnerInvitationResponseIndexRoute
  '/live-class-guest': typeof LiveClassGuestIndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/referral': typeof ReferralIndexRoute
  '/register': typeof RegisterIndexRoute
  '/study-library': typeof StudyLibraryIndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsIndexRoute
  '/user-profile': typeof UserProfileIndexRoute
  '/assessment/examination': typeof AssessmentExaminationIndexRoute
  '/assessment/reports': typeof AssessmentReportsIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/homework/list': typeof HomeworkListIndexRoute
  '/homework/reports': typeof HomeworkReportsIndexRoute
  '/live-class-guest/embed': typeof LiveClassGuestEmbedIndexRoute
  '/live-class-guest/waiting-room': typeof LiveClassGuestWaitingRoomIndexRoute
  '/login/forgot-password': typeof LoginForgotPasswordIndexRoute
  '/register/live-class': typeof RegisterLiveClassIndexRoute
  '/study-library/courses': typeof StudyLibraryCoursesIndexRoute
  '/study-library/live-class': typeof StudyLibraryLiveClassIndexRoute
  '/user-profile/edit': typeof UserProfileEditIndexRoute
  '/assessment/examination/$assessmentId/LearnerLiveTest': typeof AssessmentExaminationAssessmentIdLearnerLiveTestRoute
  '/assessment/examination/$assessmentId/assessmentPreview': typeof AssessmentExaminationAssessmentIdAssessmentPreviewRoute
  '/assessment/examination/$assessmentId': typeof AssessmentExaminationAssessmentIdIndexRoute
  '/assessment/reports/student-report': typeof AssessmentReportsStudentReportIndexRoute
  '/study-library/courses/levels': typeof StudyLibraryCoursesLevelsIndexRoute
  '/study-library/live-class/embed': typeof StudyLibraryLiveClassEmbedIndexRoute
  '/study-library/live-class/waiting-room': typeof StudyLibraryLiveClassWaitingRoomIndexRoute
  '/study-library/courses/levels/subjects': typeof StudyLibraryCoursesLevelsSubjectsIndexRoute
  '/study-library/courses/levels/subjects/modules': typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute
  '/study-library/courses/levels/subjects/modules/chapters': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute
  '/study-library/courses/levels/subjects/modules/chapters/slides': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute
}
export interface FileRoutesByTo {
  '/SessionSelectionPage': typeof SessionSelectionPageIndexRoute
  '/change-password': typeof ChangePasswordIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/delete-user': typeof DeleteUserIndexRoute
  '/institute-selection': typeof InstituteSelectionIndexRoute
  '/learner-invitation-response': typeof LearnerInvitationResponseIndexRoute
  '/live-class-guest': typeof LiveClassGuestIndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/referral': typeof ReferralIndexRoute
  '/register': typeof RegisterIndexRoute
  '/study-library': typeof StudyLibraryIndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsIndexRoute
  '/user-profile': typeof UserProfileIndexRoute
  '/assessment/examination': typeof AssessmentExaminationIndexRoute
  '/assessment/reports': typeof AssessmentReportsIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/homework/list': typeof HomeworkListIndexRoute
  '/homework/reports': typeof HomeworkReportsIndexRoute
  '/live-class-guest/embed': typeof LiveClassGuestEmbedIndexRoute
  '/live-class-guest/waiting-room': typeof LiveClassGuestWaitingRoomIndexRoute
  '/login/forgot-password': typeof LoginForgotPasswordIndexRoute
  '/register/live-class': typeof RegisterLiveClassIndexRoute
  '/study-library/courses': typeof StudyLibraryCoursesIndexRoute
  '/study-library/live-class': typeof StudyLibraryLiveClassIndexRoute
  '/user-profile/edit': typeof UserProfileEditIndexRoute
  '/assessment/examination/$assessmentId/LearnerLiveTest': typeof AssessmentExaminationAssessmentIdLearnerLiveTestRoute
  '/assessment/examination/$assessmentId/assessmentPreview': typeof AssessmentExaminationAssessmentIdAssessmentPreviewRoute
  '/assessment/examination/$assessmentId': typeof AssessmentExaminationAssessmentIdIndexRoute
  '/assessment/reports/student-report': typeof AssessmentReportsStudentReportIndexRoute
  '/study-library/courses/levels': typeof StudyLibraryCoursesLevelsIndexRoute
  '/study-library/live-class/embed': typeof StudyLibraryLiveClassEmbedIndexRoute
  '/study-library/live-class/waiting-room': typeof StudyLibraryLiveClassWaitingRoomIndexRoute
  '/study-library/courses/levels/subjects': typeof StudyLibraryCoursesLevelsSubjectsIndexRoute
  '/study-library/courses/levels/subjects/modules': typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute
  '/study-library/courses/levels/subjects/modules/chapters': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute
  '/study-library/courses/levels/subjects/modules/chapters/slides': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/SessionSelectionPage/': typeof SessionSelectionPageIndexRoute
  '/change-password/': typeof ChangePasswordIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/delete-user/': typeof DeleteUserIndexRoute
  '/institute-selection/': typeof InstituteSelectionIndexRoute
  '/learner-invitation-response/': typeof LearnerInvitationResponseIndexRoute
  '/live-class-guest/': typeof LiveClassGuestIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/referral/': typeof ReferralIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/study-library/': typeof StudyLibraryIndexRoute
  '/terms-and-conditions/': typeof TermsAndConditionsIndexRoute
  '/user-profile/': typeof UserProfileIndexRoute
  '/assessment/examination/': typeof AssessmentExaminationIndexRoute
  '/assessment/reports/': typeof AssessmentReportsIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/homework/list/': typeof HomeworkListIndexRoute
  '/homework/reports/': typeof HomeworkReportsIndexRoute
  '/live-class-guest/embed/': typeof LiveClassGuestEmbedIndexRoute
  '/live-class-guest/waiting-room/': typeof LiveClassGuestWaitingRoomIndexRoute
  '/login/forgot-password/': typeof LoginForgotPasswordIndexRoute
  '/register/live-class/': typeof RegisterLiveClassIndexRoute
  '/study-library/courses/': typeof StudyLibraryCoursesIndexRoute
  '/study-library/live-class/': typeof StudyLibraryLiveClassIndexRoute
  '/user-profile/edit/': typeof UserProfileEditIndexRoute
  '/assessment/examination/$assessmentId/LearnerLiveTest': typeof AssessmentExaminationAssessmentIdLearnerLiveTestRoute
  '/assessment/examination/$assessmentId/assessmentPreview': typeof AssessmentExaminationAssessmentIdAssessmentPreviewRoute
  '/assessment/examination/$assessmentId/': typeof AssessmentExaminationAssessmentIdIndexRoute
  '/assessment/reports/student-report/': typeof AssessmentReportsStudentReportIndexRoute
  '/study-library/courses/levels/': typeof StudyLibraryCoursesLevelsIndexRoute
  '/study-library/live-class/embed/': typeof StudyLibraryLiveClassEmbedIndexRoute
  '/study-library/live-class/waiting-room/': typeof StudyLibraryLiveClassWaitingRoomIndexRoute
  '/study-library/courses/levels/subjects/': typeof StudyLibraryCoursesLevelsSubjectsIndexRoute
  '/study-library/courses/levels/subjects/modules/': typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute
  '/study-library/courses/levels/subjects/modules/chapters/': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute
  '/study-library/courses/levels/subjects/modules/chapters/slides/': typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/SessionSelectionPage'
    | '/change-password'
    | '/dashboard'
    | '/delete-user'
    | '/institute-selection'
    | '/learner-invitation-response'
    | '/live-class-guest'
    | '/login'
    | '/logout'
    | '/privacy-policy'
    | '/referral'
    | '/register'
    | '/study-library'
    | '/terms-and-conditions'
    | '/user-profile'
    | '/assessment/examination'
    | '/assessment/reports'
    | '/dashboard/notifications'
    | '/homework/list'
    | '/homework/reports'
    | '/live-class-guest/embed'
    | '/live-class-guest/waiting-room'
    | '/login/forgot-password'
    | '/register/live-class'
    | '/study-library/courses'
    | '/study-library/live-class'
    | '/user-profile/edit'
    | '/assessment/examination/$assessmentId/LearnerLiveTest'
    | '/assessment/examination/$assessmentId/assessmentPreview'
    | '/assessment/examination/$assessmentId'
    | '/assessment/reports/student-report'
    | '/study-library/courses/levels'
    | '/study-library/live-class/embed'
    | '/study-library/live-class/waiting-room'
    | '/study-library/courses/levels/subjects'
    | '/study-library/courses/levels/subjects/modules'
    | '/study-library/courses/levels/subjects/modules/chapters'
    | '/study-library/courses/levels/subjects/modules/chapters/slides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/SessionSelectionPage'
    | '/change-password'
    | '/dashboard'
    | '/delete-user'
    | '/institute-selection'
    | '/learner-invitation-response'
    | '/live-class-guest'
    | '/login'
    | '/logout'
    | '/privacy-policy'
    | '/referral'
    | '/register'
    | '/study-library'
    | '/terms-and-conditions'
    | '/user-profile'
    | '/assessment/examination'
    | '/assessment/reports'
    | '/dashboard/notifications'
    | '/homework/list'
    | '/homework/reports'
    | '/live-class-guest/embed'
    | '/live-class-guest/waiting-room'
    | '/login/forgot-password'
    | '/register/live-class'
    | '/study-library/courses'
    | '/study-library/live-class'
    | '/user-profile/edit'
    | '/assessment/examination/$assessmentId/LearnerLiveTest'
    | '/assessment/examination/$assessmentId/assessmentPreview'
    | '/assessment/examination/$assessmentId'
    | '/assessment/reports/student-report'
    | '/study-library/courses/levels'
    | '/study-library/live-class/embed'
    | '/study-library/live-class/waiting-room'
    | '/study-library/courses/levels/subjects'
    | '/study-library/courses/levels/subjects/modules'
    | '/study-library/courses/levels/subjects/modules/chapters'
    | '/study-library/courses/levels/subjects/modules/chapters/slides'
  id:
    | '__root__'
    | '/SessionSelectionPage/'
    | '/change-password/'
    | '/dashboard/'
    | '/delete-user/'
    | '/institute-selection/'
    | '/learner-invitation-response/'
    | '/live-class-guest/'
    | '/login/'
    | '/logout/'
    | '/privacy-policy/'
    | '/referral/'
    | '/register/'
    | '/study-library/'
    | '/terms-and-conditions/'
    | '/user-profile/'
    | '/assessment/examination/'
    | '/assessment/reports/'
    | '/dashboard/notifications/'
    | '/homework/list/'
    | '/homework/reports/'
    | '/live-class-guest/embed/'
    | '/live-class-guest/waiting-room/'
    | '/login/forgot-password/'
    | '/register/live-class/'
    | '/study-library/courses/'
    | '/study-library/live-class/'
    | '/user-profile/edit/'
    | '/assessment/examination/$assessmentId/LearnerLiveTest'
    | '/assessment/examination/$assessmentId/assessmentPreview'
    | '/assessment/examination/$assessmentId/'
    | '/assessment/reports/student-report/'
    | '/study-library/courses/levels/'
    | '/study-library/live-class/embed/'
    | '/study-library/live-class/waiting-room/'
    | '/study-library/courses/levels/subjects/'
    | '/study-library/courses/levels/subjects/modules/'
    | '/study-library/courses/levels/subjects/modules/chapters/'
    | '/study-library/courses/levels/subjects/modules/chapters/slides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SessionSelectionPageIndexRoute: typeof SessionSelectionPageIndexRoute
  ChangePasswordIndexRoute: typeof ChangePasswordIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DeleteUserIndexRoute: typeof DeleteUserIndexRoute
  InstituteSelectionIndexRoute: typeof InstituteSelectionIndexRoute
  LearnerInvitationResponseIndexRoute: typeof LearnerInvitationResponseIndexRoute
  LiveClassGuestIndexRoute: typeof LiveClassGuestIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  ReferralIndexRoute: typeof ReferralIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  StudyLibraryIndexRoute: typeof StudyLibraryIndexRoute
  TermsAndConditionsIndexRoute: typeof TermsAndConditionsIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
  AssessmentExaminationIndexRoute: typeof AssessmentExaminationIndexRoute
  AssessmentReportsIndexRoute: typeof AssessmentReportsIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  HomeworkListIndexRoute: typeof HomeworkListIndexRoute
  HomeworkReportsIndexRoute: typeof HomeworkReportsIndexRoute
  LiveClassGuestEmbedIndexRoute: typeof LiveClassGuestEmbedIndexRoute
  LiveClassGuestWaitingRoomIndexRoute: typeof LiveClassGuestWaitingRoomIndexRoute
  LoginForgotPasswordIndexRoute: typeof LoginForgotPasswordIndexRoute
  RegisterLiveClassIndexRoute: typeof RegisterLiveClassIndexRoute
  StudyLibraryCoursesIndexRoute: typeof StudyLibraryCoursesIndexRoute
  StudyLibraryLiveClassIndexRoute: typeof StudyLibraryLiveClassIndexRoute
  UserProfileEditIndexRoute: typeof UserProfileEditIndexRoute
  AssessmentExaminationAssessmentIdLearnerLiveTestRoute: typeof AssessmentExaminationAssessmentIdLearnerLiveTestRoute
  AssessmentExaminationAssessmentIdAssessmentPreviewRoute: typeof AssessmentExaminationAssessmentIdAssessmentPreviewRoute
  AssessmentExaminationAssessmentIdIndexRoute: typeof AssessmentExaminationAssessmentIdIndexRoute
  AssessmentReportsStudentReportIndexRoute: typeof AssessmentReportsStudentReportIndexRoute
  StudyLibraryCoursesLevelsIndexRoute: typeof StudyLibraryCoursesLevelsIndexRoute
  StudyLibraryLiveClassEmbedIndexRoute: typeof StudyLibraryLiveClassEmbedIndexRoute
  StudyLibraryLiveClassWaitingRoomIndexRoute: typeof StudyLibraryLiveClassWaitingRoomIndexRoute
  StudyLibraryCoursesLevelsSubjectsIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsIndexRoute
  StudyLibraryCoursesLevelsSubjectsModulesIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRoute
  StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute
  StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-profile/': {
      id: '/user-profile/'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions/': {
      id: '/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/': {
      id: '/study-library/'
      path: '/study-library'
      fullPath: '/study-library'
      preLoaderRoute: typeof StudyLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral/': {
      id: '/referral/'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-class-guest/': {
      id: '/live-class-guest/'
      path: '/live-class-guest'
      fullPath: '/live-class-guest'
      preLoaderRoute: typeof LiveClassGuestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner-invitation-response/': {
      id: '/learner-invitation-response/'
      path: '/learner-invitation-response'
      fullPath: '/learner-invitation-response'
      preLoaderRoute: typeof LearnerInvitationResponseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute-selection/': {
      id: '/institute-selection/'
      path: '/institute-selection'
      fullPath: '/institute-selection'
      preLoaderRoute: typeof InstituteSelectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-user/': {
      id: '/delete-user/'
      path: '/delete-user'
      fullPath: '/delete-user'
      preLoaderRoute: typeof DeleteUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password/': {
      id: '/change-password/'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SessionSelectionPage/': {
      id: '/SessionSelectionPage/'
      path: '/SessionSelectionPage'
      fullPath: '/SessionSelectionPage'
      preLoaderRoute: typeof SessionSelectionPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-profile/edit/': {
      id: '/user-profile/edit/'
      path: '/user-profile/edit'
      fullPath: '/user-profile/edit'
      preLoaderRoute: typeof UserProfileEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/live-class/': {
      id: '/study-library/live-class/'
      path: '/study-library/live-class'
      fullPath: '/study-library/live-class'
      preLoaderRoute: typeof StudyLibraryLiveClassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/courses/': {
      id: '/study-library/courses/'
      path: '/study-library/courses'
      fullPath: '/study-library/courses'
      preLoaderRoute: typeof StudyLibraryCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/live-class/': {
      id: '/register/live-class/'
      path: '/register/live-class'
      fullPath: '/register/live-class'
      preLoaderRoute: typeof RegisterLiveClassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/forgot-password/': {
      id: '/login/forgot-password/'
      path: '/login/forgot-password'
      fullPath: '/login/forgot-password'
      preLoaderRoute: typeof LoginForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-class-guest/waiting-room/': {
      id: '/live-class-guest/waiting-room/'
      path: '/live-class-guest/waiting-room'
      fullPath: '/live-class-guest/waiting-room'
      preLoaderRoute: typeof LiveClassGuestWaitingRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-class-guest/embed/': {
      id: '/live-class-guest/embed/'
      path: '/live-class-guest/embed'
      fullPath: '/live-class-guest/embed'
      preLoaderRoute: typeof LiveClassGuestEmbedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework/reports/': {
      id: '/homework/reports/'
      path: '/homework/reports'
      fullPath: '/homework/reports'
      preLoaderRoute: typeof HomeworkReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework/list/': {
      id: '/homework/list/'
      path: '/homework/list'
      fullPath: '/homework/list'
      preLoaderRoute: typeof HomeworkListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/reports/': {
      id: '/assessment/reports/'
      path: '/assessment/reports'
      fullPath: '/assessment/reports'
      preLoaderRoute: typeof AssessmentReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/examination/': {
      id: '/assessment/examination/'
      path: '/assessment/examination'
      fullPath: '/assessment/examination'
      preLoaderRoute: typeof AssessmentExaminationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/live-class/waiting-room/': {
      id: '/study-library/live-class/waiting-room/'
      path: '/study-library/live-class/waiting-room'
      fullPath: '/study-library/live-class/waiting-room'
      preLoaderRoute: typeof StudyLibraryLiveClassWaitingRoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/live-class/embed/': {
      id: '/study-library/live-class/embed/'
      path: '/study-library/live-class/embed'
      fullPath: '/study-library/live-class/embed'
      preLoaderRoute: typeof StudyLibraryLiveClassEmbedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/courses/levels/': {
      id: '/study-library/courses/levels/'
      path: '/study-library/courses/levels'
      fullPath: '/study-library/courses/levels'
      preLoaderRoute: typeof StudyLibraryCoursesLevelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/reports/student-report/': {
      id: '/assessment/reports/student-report/'
      path: '/assessment/reports/student-report'
      fullPath: '/assessment/reports/student-report'
      preLoaderRoute: typeof AssessmentReportsStudentReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/examination/$assessmentId/': {
      id: '/assessment/examination/$assessmentId/'
      path: '/assessment/examination/$assessmentId'
      fullPath: '/assessment/examination/$assessmentId'
      preLoaderRoute: typeof AssessmentExaminationAssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/examination/$assessmentId/assessmentPreview': {
      id: '/assessment/examination/$assessmentId/assessmentPreview'
      path: '/assessment/examination/$assessmentId/assessmentPreview'
      fullPath: '/assessment/examination/$assessmentId/assessmentPreview'
      preLoaderRoute: typeof AssessmentExaminationAssessmentIdAssessmentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/examination/$assessmentId/LearnerLiveTest': {
      id: '/assessment/examination/$assessmentId/LearnerLiveTest'
      path: '/assessment/examination/$assessmentId/LearnerLiveTest'
      fullPath: '/assessment/examination/$assessmentId/LearnerLiveTest'
      preLoaderRoute: typeof AssessmentExaminationAssessmentIdLearnerLiveTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/courses/levels/subjects/': {
      id: '/study-library/courses/levels/subjects/'
      path: '/study-library/courses/levels/subjects'
      fullPath: '/study-library/courses/levels/subjects'
      preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/courses/levels/subjects/modules/': {
      id: '/study-library/courses/levels/subjects/modules/'
      path: '/study-library/courses/levels/subjects/modules'
      fullPath: '/study-library/courses/levels/subjects/modules'
      preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/courses/levels/subjects/modules/chapters/': {
      id: '/study-library/courses/levels/subjects/modules/chapters/'
      path: '/study-library/courses/levels/subjects/modules/chapters'
      fullPath: '/study-library/courses/levels/subjects/modules/chapters'
      preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-library/courses/levels/subjects/modules/chapters/slides/': {
      id: '/study-library/courses/levels/subjects/modules/chapters/slides/'
      path: '/study-library/courses/levels/subjects/modules/chapters/slides'
      fullPath: '/study-library/courses/levels/subjects/modules/chapters/slides'
      preLoaderRoute: typeof StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SessionSelectionPageIndexRoute: SessionSelectionPageIndexRoute,
  ChangePasswordIndexRoute: ChangePasswordIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DeleteUserIndexRoute: DeleteUserIndexRoute,
  InstituteSelectionIndexRoute: InstituteSelectionIndexRoute,
  LearnerInvitationResponseIndexRoute: LearnerInvitationResponseIndexRoute,
  LiveClassGuestIndexRoute: LiveClassGuestIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  ReferralIndexRoute: ReferralIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  StudyLibraryIndexRoute: StudyLibraryIndexRoute,
  TermsAndConditionsIndexRoute: TermsAndConditionsIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
  AssessmentExaminationIndexRoute: AssessmentExaminationIndexRoute,
  AssessmentReportsIndexRoute: AssessmentReportsIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  HomeworkListIndexRoute: HomeworkListIndexRoute,
  HomeworkReportsIndexRoute: HomeworkReportsIndexRoute,
  LiveClassGuestEmbedIndexRoute: LiveClassGuestEmbedIndexRoute,
  LiveClassGuestWaitingRoomIndexRoute: LiveClassGuestWaitingRoomIndexRoute,
  LoginForgotPasswordIndexRoute: LoginForgotPasswordIndexRoute,
  RegisterLiveClassIndexRoute: RegisterLiveClassIndexRoute,
  StudyLibraryCoursesIndexRoute: StudyLibraryCoursesIndexRoute,
  StudyLibraryLiveClassIndexRoute: StudyLibraryLiveClassIndexRoute,
  UserProfileEditIndexRoute: UserProfileEditIndexRoute,
  AssessmentExaminationAssessmentIdLearnerLiveTestRoute:
    AssessmentExaminationAssessmentIdLearnerLiveTestRoute,
  AssessmentExaminationAssessmentIdAssessmentPreviewRoute:
    AssessmentExaminationAssessmentIdAssessmentPreviewRoute,
  AssessmentExaminationAssessmentIdIndexRoute:
    AssessmentExaminationAssessmentIdIndexRoute,
  AssessmentReportsStudentReportIndexRoute:
    AssessmentReportsStudentReportIndexRoute,
  StudyLibraryCoursesLevelsIndexRoute: StudyLibraryCoursesLevelsIndexRoute,
  StudyLibraryLiveClassEmbedIndexRoute: StudyLibraryLiveClassEmbedIndexRoute,
  StudyLibraryLiveClassWaitingRoomIndexRoute:
    StudyLibraryLiveClassWaitingRoomIndexRoute,
  StudyLibraryCoursesLevelsSubjectsIndexRoute:
    StudyLibraryCoursesLevelsSubjectsIndexRoute,
  StudyLibraryCoursesLevelsSubjectsModulesIndexRoute:
    StudyLibraryCoursesLevelsSubjectsModulesIndexRoute,
  StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute:
    StudyLibraryCoursesLevelsSubjectsModulesChaptersIndexRoute,
  StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute:
    StudyLibraryCoursesLevelsSubjectsModulesChaptersSlidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
