/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DashboardIndexImport } from "./routes/dashboard/index";
import { Route as DashboardStudentsIndexImport } from "./routes/dashboard/students/index";

// Create/Update Routes

const DashboardIndexRoute = DashboardIndexImport.update({
    path: "/dashboard/",
    getParentRoute: () => rootRoute,
} as any);

const DashboardStudentsIndexRoute = DashboardStudentsIndexImport.update({
    path: "/dashboard/students/",
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/dashboard/": {
            id: "/dashboard/";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardIndexImport;
            parentRoute: typeof rootRoute;
        };
        "/dashboard/students/": {
            id: "/dashboard/students/";
            path: "/dashboard/students";
            fullPath: "/dashboard/students";
            preLoaderRoute: typeof DashboardStudentsIndexImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
    DashboardIndexRoute,
    DashboardStudentsIndexRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard/",
        "/dashboard/students/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/dashboard/students/": {
      "filePath": "dashboard/students/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
